package org.sliqado.sandbox

import android.content.Context
import android.graphics.*
import android.view.MotionEvent
import android.view.View
import kotlin.math.*
import kotlin.random.Random

class GameView(c:Context):View(c){
 companion object{const val AIR=0;const val SAND=1;const val WATER=2;const val STONE=3;const val WOOD=4;const val FIRE=5;const val OIL=6;const val SEED=7;const val ACID=8;const val SALT=9;const val STEAM=10;const val ICE=11;const val LAVA=12;const val METAL=13;const val COPPER=14;const val WIRE=15;const val BATTERY=16;const val HEATER=17;const val COOLER=18;const val LAMP=19;const val SPARK=20;const val GUNPOWDER=21;const val GLASS=22;const val COAL=23;const val SMOKE=24;const val GAS=25;const val SALTWATER=26;const val MUD=27;const val SNOW=28;const val NITROGEN=29;const val ANT=30;const val SUGAR=31;const val WAX=32;const val MWAX=33;const val MMETAL=34;const val MCOPPER=35;const val MGLASS=36;const val MERCURY=37;const val ALCOHOL=38;const val FOAM=39;const val CONCRETE=40;const val CEMENT=41;const val CLAY=42;const val URANIUM=43;const val PLASMA=44;const val ASH=45;const val CHARCOAL=46;const val HONEY=47;const val SPONGE=48}
 data class D(val id:Int,val n:String,val s:String,val col:Int,val state:Int,val cond:Boolean=false,val r:Float=6f,val flam:Boolean=false)
 private val ds=arrayOfNulls<D>(49);private val menu=ArrayList<D>()
 private val W=160;private val H=240;private val N=W*H;private val g=ByteArray(N);private val life=ShortArray(N);private val t=FloatArray(N){20f};private val v=FloatArray(N);private val moved=IntArray(N);private val t2=FloatArray(N);private val pix=IntArray(N);private val q=IntArray(N);private val bmp=Bitmap.createBitmap(W,H,Bitmap.Config.ARGB_8888);private val src=Rect(0,0,W,H);private val dst=RectF();private val paint=Paint();private val line=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=0xff303030.toInt();strokeWidth=2f};private val txt=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.BLACK;textAlign=Paint.Align.CENTER;typeface=Typeface.DEFAULT_BOLD};private val rnd=Random(System.nanoTime())
 private var sel=SAND;private var eraser=false;private var pause=false;private var view=0;private var tick=1;private var frame=0;private var sb=0f;private var tw=0f;private var th=0f;private var scroll=0f;private var world=false;private var panel=false;private var lx=0f;private var ly=0f;private var py=0f
 private val loop=object:Runnable{override fun run(){if(!pause&&frame%2==0)step();frame++;invalidate();postOnAnimation(this)}}
 init{isFocusable=true;keepScreenOn=true;defs();demo();postOnAnimation(loop)}
 private fun a(id:Int,n:String,s:String,c:Int,st:Int,co:Boolean=false,r:Float=6f,f:Boolean=false){val d=D(id,n,s,c,st,co,r,f);ds[id]=d;menu.add(d)}
 private fun defs(){a(SAND,"Sand","Sa",0xffd9b85d.toInt(),1);a(WATER,"Water","Wa",0xff3b8eea.toInt(),2);a(STONE,"Stone","St",0xff858987.toInt(),0);a(WOOD,"Wood","Wo",0xffa2673d.toInt(),0,f=true);a(FIRE,"Fire","Fi",0xffff6b18.toInt(),3);a(OIL,"Oil","Oi",0xff67512f.toInt(),2,f=true);a(SEED,"Seeds","Se",0xff8c6b2f.toInt(),1,f=true);a(ACID,"Acid","Ac",0xff9dde39.toInt(),2);a(SALT,"Salt","Sl",0xffeee9dc.toInt(),1);a(STEAM,"Steam","Vm",0xffb6c5ca.toInt(),3);a(ICE,"Ice","Ic",0xff9edcf1.toInt(),0);a(LAVA,"Lava","Lv",0xffef3d14.toInt(),2);a(METAL,"Metal","Me",0xff9aa4a9.toInt(),0,true,5f);a(COPPER,"Copper","Cu",0xffc8793e.toInt(),0,true,2f);a(WIRE,"Wire","Wi",0xffd7a63e.toInt(),0,true,2f);a(BATTERY,"Battery","Ba",0xff75c75d.toInt(),0,true,1f);a(HEATER,"Heater","Ht",0xffdd6b43.toInt(),0,true,3f);a(COOLER,"Cooler","Cl",0xff59b9e5.toInt(),0,true,3f);a(LAMP,"Lamp","La",0xffffe76a.toInt(),0,true,4f);a(SPARK,"Spark","Sp",0xff9de9ff.toInt(),3,true,1f);a(GUNPOWDER,"Gunpowder","Gp",0xff4c4943.toInt(),1,f=true);a(GLASS,"Glass","Gl",0xff9bc3cc.toInt(),0);a(COAL,"Coal","Co",0xff323638.toInt(),1,f=true);a(SMOKE,"Smoke","Sm",0xff5c6467.toInt(),3);a(GAS,"Gas","Ga",0xffb49d69.toInt(),3,f=true);a(SALTWATER,"Salt Water","SW",0xff4da2c9.toInt(),2,true,6f);a(MUD,"Mud","Mu",0xff75543b.toInt(),1);a(SNOW,"Snow","Sn",0xffe0f5fb.toInt(),1);a(NITROGEN,"Liquid N2","N2",0xffaeeeff.toInt(),2);a(ANT,"Ants","An",0xff171717.toInt(),4);a(SUGAR,"Sugar","Su",0xfffff1cf.toInt(),1,f=true);a(WAX,"Wax","Wx",0xffffe1a3.toInt(),0,f=true);a(MWAX,"Molten Wax","MW",0xffffb34f.toInt(),2,f=true);a(MMETAL,"Molten Metal","MM",0xffff8b48.toInt(),2,true,4f);a(MCOPPER,"Molten Copper","MC",0xffff7138.toInt(),2,true,2f);a(MGLASS,"Molten Glass","MG",0xffffc97e.toInt(),2);a(MERCURY,"Mercury","Hg",0xffb9c3c8.toInt(),2,true,3f);a(ALCOHOL,"Alcohol","Al",0xffcddff4.toInt(),2,f=true);a(FOAM,"Foam","Fo",0xfff1f4ef.toInt(),1);a(CONCRETE,"Concrete","Cr",0xff9b9a91.toInt(),0);a(CEMENT,"Cement","Ce",0xffbeb9ae.toInt(),1);a(CLAY,"Clay","Cy",0xffa76d52.toInt(),1);a(URANIUM,"Uranium","Ur",0xff83bf4b.toInt(),1,true,8f);a(PLASMA,"Plasma","Pl",0xffff65ef.toInt(),3,true,1f);a(ASH,"Ash","As",0xff77736c.toInt(),1);a(CHARCOAL,"Charcoal","Ch",0xff272727.toInt(),1,f=true);a(HONEY,"Honey","Ho",0xffd79118.toInt(),2,f=true);a(SPONGE,"Sponge","Sg",0xffffdb55.toInt(),0,f=true)}
 private fun id(x:Int,y:Int)=x+y*W;private fun inside(x:Int,y:Int)=x>=0&&x<W&&y>=0&&y<H;private fun at(x:Int,y:Int)=if(inside(x,y))g[id(x,y)].toInt()and 255 else STONE
 private fun baseT(e:Int)=when(e){LAVA->1250f;FIRE->820f;PLASMA->2200f;SPARK->550f;MMETAL->1550f;MCOPPER->1180f;MGLASS->1500f;MWAX->85f;ICE->-12f;SNOW->-8f;NITROGEN->-196f;else->20f}
 private fun set(x:Int,y:Int,e:Int,l:Int=0,tt:Float?=null){if(!inside(x,y))return;val i=id(x,y);g[i]=e.toByte();life[i]=l.toShort();t[i]=tt?:baseT(e);v[i]=0f;moved[i]=tick};private fun clear(i:Int){g[i]=0;life[i]=0;t[i]=20f;v[i]=0f;moved[i]=tick};private fun sw(a:Int,b:Int){var z=g[a];g[a]=g[b];g[b]=z;var s=life[a];life[a]=life[b];life[b]=s;var f=t[a];t[a]=t[b];t[b]=f;f=v[a];v[a]=v[b];v[b]=f;moved[a]=tick;moved[b]=tick}
 private fun neigh(x:Int,y:Int,e:Int):Int{for(dy in-1..1)for(dx in-1..1){if(dx==0&&dy==0)continue;val nx=x+dx;val ny=y+dy;if(inside(nx,ny)){val i=id(nx,ny);if((g[i].toInt()and 255)==e)return i}};return-1};private fun near(x:Int,y:Int,vararg es:Int):Boolean{for(e in es)if(neigh(x,y,e)>=0)return true;return false}
 private fun fluid(e:Int)=e==WATER||e==OIL||e==ACID||e==SALTWATER||e==LAVA||e==NITROGEN||e==MWAX||e==MMETAL||e==MCOPPER||e==MGLASS||e==MERCURY||e==ALCOHOL||e==HONEY
 private fun powder(x:Int,y:Int,slow:Int=1){if(slow>1&&tick%slow!=0)return;val i=id(x,y);if(at(x,y+1)==AIR||fluid(at(x,y+1))){sw(i,id(x,y+1));return};val s=if(rnd.nextBoolean())1 else-1;for(dx in intArrayOf(s,-s))if(inside(x+dx,y+1)&&(at(x+dx,y+1)==AIR||fluid(at(x+dx,y+1)))){sw(i,id(x+dx,y+1));return}}
 private fun liquid(x:Int,y:Int,spread:Int=4,slow:Int=1){if(slow>1&&tick%slow!=0)return;val i=id(x,y);if(y+1<H&&at(x,y+1)==AIR){sw(i,id(x,y+1));return};val s=if(rnd.nextBoolean())1 else-1;for(d in 1..spread)for(k in intArrayOf(s,-s)){val nx=x+k*d;if(inside(nx,y)&&at(nx,y)==AIR){sw(i,id(nx,y));return}}}
 private fun gas(x:Int,y:Int){val i=id(x,y);if(y>0&&at(x,y-1)==AIR){sw(i,id(x,y-1));return};val s=if(rnd.nextBoolean())1 else-1;if(inside(x+s,y-1)&&at(x+s,y-1)==AIR)sw(i,id(x+s,y-1))else if(inside(x+s,y)&&at(x+s,y)==AIR)sw(i,id(x+s,y))}
 private fun phase(i:Int,e:Int){val q=t[i];when(e){WATER,SALTWATER->if(q<0)g[i]=ICE.toByte()else if(q>104)g[i]=STEAM.toByte();ICE,SNOW->if(q>1)g[i]=WATER.toByte();STEAM->if(q<88)g[i]=WATER.toByte();WAX->if(q>62)g[i]=MWAX.toByte();MWAX->if(q<54)g[i]=WAX.toByte();METAL->if(q>1450)g[i]=MMETAL.toByte();MMETAL->if(q<1330)g[i]=METAL.toByte();COPPER,WIRE->if(q>1085)g[i]=MCOPPER.toByte();MCOPPER->if(q<980)g[i]=COPPER.toByte();GLASS->if(q>1400)g[i]=MGLASS.toByte();MGLASS->if(q<850)g[i]=GLASS.toByte();STONE->if(q>1350)g[i]=LAVA.toByte();LAVA->if(q<680)g[i]=STONE.toByte();SUGAR->if(q>185)g[i]=HONEY.toByte();ALCOHOL->if(q>78)g[i]=GAS.toByte();MERCURY->if(q>357)g[i]=GAS.toByte();CLAY->if(q>1050)g[i]=STONE.toByte()}}
 private fun ignite(x:Int,y:Int){for(dy in-1..1)for(dx in-1..1){val nx=x+dx;val ny=y+dy;if(!inside(nx,ny))continue;val i=id(nx,ny);val e=g[i].toInt()and 255;if(ds[e]?.flam==true&&rnd.nextFloat()<(if(e==GAS||e==GUNPOWDER).25f else .04f)){g[i]=FIRE.toByte();life[i]=0;t[i]=max(t[i],700f)}}}
 private fun ant(x:Int,y:Int){val i=id(x,y);if(t[i]>80||near(x,y,FIRE,LAVA,ACID,PLASMA)){clear(i);return};var bx=0;var by=0;loop@for(r in 1..5)for(dy in-r..r)for(dx in-r..r)if(inside(x+dx,y+dy)&&at(x+dx,y+dy)==SEED){bx=dx.sign;by=dy.sign;break@loop};if(abs(bx)<=1&&abs(by)<=1&&near(x,y,SEED)){val s=neigh(x,y,SEED);if(s>=0){clear(s);return}};val dx=if(bx!=0)bx else if(rnd.nextBoolean())1 else-1;val dy=if(by!=0)by else 0;val nx=x+dx;val ny=y+dy;if(inside(nx,ny)&&at(nx,ny)==AIR&&(at(nx,ny+1)!=AIR||at(nx-1,ny)!=AIR||at(nx+1,ny)!=AIR))sw(i,id(nx,ny))}
 private val Int.sign:Int get()=if(this<0)-1 else if(this>0)1 else 0
 private fun cell(x:Int,y:Int){val i=id(x,y);if(moved[i]==tick)return;val e=g[i].toInt()and 255;if(e==AIR)return;phase(i,e);if((g[i].toInt()and 255)!=e)return;when(e){SAND,SALT,SUGAR,CEMENT,CLAY,ASH,CHARCOAL,COAL,GUNPOWDER->powder(x,y);MUD->powder(x,y,2);SNOW->powder(x,y);URANIUM->{powder(x,y);t[i]+=.2f};WATER,SALTWATER,ACID,MERCURY,ALCOHOL->liquid(x,y,5);OIL->liquid(x,y,6);HONEY->liquid(x,y,3,3);MWAX->liquid(x,y,3,2);LAVA,MMETAL,MCOPPER,MGLASS->liquid(x,y,2,2);STEAM,SMOKE,GAS->{life[i]=(life[i]+1).toShort();gas(x,y)};FIRE->{life[i]=(life[i]+1).toShort();t[i]=max(t[i],820f);ignite(x,y);if(near(x,y,WATER,SALTWATER,NITROGEN)&&rnd.nextFloat()<.2f){clear(i);return};if((life[i].toInt()and 65535)>100){g[i]=if(rnd.nextBoolean())SMOKE.toByte()else ASH.toByte();life[i]=0}else gas(x,y)};SPARK->{life[i]=(life[i]+1).toShort();t[i]=550f;ignite(x,y);if((life[i].toInt()and 65535)>18)clear(i)else gas(x,y)};PLASMA->{life[i]=(life[i]+1).toShort();t[i]=2200f;ignite(x,y);gas(x,y)};NITROGEN->{val age=(life[i].toInt()and 65535)+1;life[i]=age.toShort();for(dy in-1..1)for(dx in-1..1)if(inside(x+dx,y+dy))t[id(x+dx,y+dy)]-=3f;val warm=max(0f,t[i]+196f);if(age>max(25f,95f-warm*.18f)){clear(i);return};liquid(x,y,5)};SEED->{powder(x,y);if((g[i].toInt()and255)==SEED&&t[i]in 4f..46f&&near(x,y,WATER,SALTWATER)&&(at(x,y+1)==MUD||at(x,y+1)==SAND)){life[i]=(life[i]+1).toShort();if((life[i].toInt()and65535)>45&&rnd.nextFloat()<.02f&&y>0&&at(x,y-1)==AIR)set(x,y-1,SEED,80,t[i])}};ANT->ant(x,y);SPONGE->{if(near(x,y,WATER,SALTWATER)&&life[i]<200)life[i]++}}
  if(e==GUNPOWDER&&(t[i]>190||near(x,y,FIRE,SPARK,PLASMA))){for(dy in-3..3)for(dx in-3..3)if(inside(x+dx,y+dy)){val j=id(x+dx,y+dy);t[j]+=250f;if((g[j].toInt()and255)==GUNPOWDER||rnd.nextFloat()<.12f)g[j]=FIRE.toByte()}}
  if(e==SALT){val w=neigh(x,y,WATER);if(w>=0&&rnd.nextFloat()<.12f){g[w]=SALTWATER.toByte();clear(i)}};if(e==WATER){val s=neigh(x,y,SAND);if(s>=0&&rnd.nextFloat()<.001f)g[s]=MUD.toByte()};if(e==CEMENT&&near(x,y,WATER)&&rnd.nextFloat()<.04f)g[i]=CONCRETE.toByte();if(ds[e]?.flam==true&&(t[i]>320||near(x,y,FIRE,SPARK,PLASMA))&&rnd.nextFloat()<.035f){g[i]=FIRE.toByte();life[i]=0}}
 private fun conductive(e:Int)=ds.getOrNull(e)?.cond==true||e==SALTWATER||e==MERCURY||e==PLASMA
 private fun electricity(){java.util.Arrays.fill(v,0f);var h=0;var z=0;for(i in 0 until N){val e=g[i].toInt()and255;if(e==BATTERY){v[i]=100f;q[z++]=i}else if(e==SPARK||e==PLASMA){v[i]=75f;q[z++]=i}};while(h<z){val i=q[h++];val x=i%W;val y=i/W;fun push(j:Int){val e=g[j].toInt()and255;if(!conductive(e))return;val nv=v[i]-(ds[e]?.r?:6f);if(nv>v[j]+.5f){v[j]=nv;if(z<N)q[z++]=j}};if(x>0)push(i-1);if(x<W-1)push(i+1);if(y>0)push(i-W);if(y<H-1)push(i+W)};for(i in 0 until N)when(g[i].toInt()and255){HEATER->if(v[i]>8)t[i]+=18f;COOLER->if(v[i]>8)t[i]-=16f;LAMP->if(v[i]>8)t[i]+=.6f}}
 private fun heat(){for(i in 0 until N)t2[i]=t[i];for(y in 1 until H-1)for(x in 1 until W-1){val i=id(x,y);val e=g[i].toInt()and255;val target=when(e){LAVA->1250f;FIRE->820f;PLASMA->2200f;MMETAL->1550f;MCOPPER->1180f;MGLASS->1500f;NITROGEN->-196f;ICE->-12f;SNOW->-8f;else->20f};if(e==LAVA||e==FIRE||e==PLASMA||e==MMETAL||e==MCOPPER||e==MGLASS||e==NITROGEN)t2[i]+=(target-t[i])*.08f;val k=when(e){COPPER,MCOPPER->.16f;METAL,MMETAL,WIRE->.12f;WATER,SALTWATER,MERCURY->.08f;STONE,CONCRETE,GLASS->.05f;else->.025f};val av=(t[i-1]+t[i+1]+t[i-W]+t[i+W])*.25f;t2[i]+=(av-t[i])*k};for(i in 0 until N)t[i]=t2[i].coerceIn(-210f,2600f)}
 private fun step(){tick++;if(tick==Int.MAX_VALUE){java.util.Arrays.fill(moved,0);tick=1};if(tick%3==0)electricity();if(tick%4==0)heat();for(y in H-2 downTo 0)for(x in if(rnd.nextBoolean())0 until W else W-1 downTo 0){val e=at(x,y);if(e!=FIRE&&e!=STEAM&&e!=SMOKE&&e!=GAS&&e!=PLASMA&&e!=SPARK)cell(x,y)};for(y in 1 until H)for(x in 0 until W){val e=at(x,y);if(e==FIRE||e==STEAM||e==SMOKE||e==GAS||e==PLASMA||e==SPARK)cell(x,y)}}
 private fun blend(a:Int,b:Int,f:Float):Int{val u=f.coerceIn(0f,1f);return Color.rgb((Color.red(a)+(Color.red(b)-Color.red(a))*u).toInt(),(Color.green(a)+(Color.green(b)-Color.green(a))*u).toInt(),(Color.blue(a)+(Color.blue(b)-Color.blue(a))*u).toInt())};private fun hcol(x:Float)=when{ x<-100->0xff505aff.toInt();x<0->blend(0xff505aff.toInt(),0xff50dcff.toInt(),(x+100)/100);x<100->blend(0xff50dcff.toInt(),0xffffdc46.toInt(),x/100);x<700->blend(0xffffdc46.toInt(),0xffff4614.toInt(),(x-100)/600);else->blend(0xffff4614.toInt(),Color.WHITE,(x-700)/1200)}
 private fun mcol(i:Int,e:Int):Int{if(e==AIR)return 0xff000018.toInt();var c=ds[e]?.col?:Color.MAGENTA;if(e==SEED&&(life[i].toInt()and65535)>45)c=0xff59b95f.toInt();if(e==LAMP&&v[i]>8)c=0xfffff6aa.toInt();if(t[i]>80)c=blend(c,if(t[i]>900)Color.WHITE else 0xffff5a22.toInt(),min(1f,(t[i]-80)/900));else if(t[i]<0)c=blend(c,0xff62c8ff.toInt(),min(.75f,-t[i]/200));return c}
 private fun render(){for(i in 0 until N){val e=g[i].toInt()and255;pix[i]=when(view){0->mcol(i,e);1->if(e==AIR)0xff05051a.toInt()else hcol(t[i]);else->if(e==AIR)0xff030315.toInt()else if(v[i]>1)blend(0xff423300.toInt(),0xffffff68.toInt(),v[i]/100)else blend(mcol(i,e),0xff0b1020.toInt(),.72f)}};bmp.setPixels(pix,0,W,0,0,W,H)}
 override fun onDraw(c:Canvas){super.onDraw(c);c.drawColor(0xff000018.toInt());sb=height*.68f;tw=width/6f;th=(height-sb)/4f;render();dst.set(0f,0f,width.toFloat(),sb);paint.isFilterBitmap=false;c.drawBitmap(bmp,src,dst,paint);controls(c);elements(c)}
 private fun tile(c:Canvas,col:Int,y:Float,bg:Int,big:String,small:String="",active:Boolean=false){val l=col*tw;paint.color=if(active)blend(bg,Color.WHITE,.16f)else bg;paint.style=Paint.Style.FILL;c.drawRect(l,y,l+tw,y+th,paint);c.drawRect(l,y,l+tw,y+th,line);txt.textSize=th*.30f;c.drawText(big,l+tw/2,y+th*.45f,txt);txt.textSize=th*.10f;c.drawText(small,l+tw/2,y+th*.78f,txt)}
 private fun controls(c:Canvas){tile(c,0,sb,0xff858585.toInt(),"NEW","clear");tile(c,1,sb,0xff858585.toInt(),arrayOf("MAT","HOT","ELE")[view],"view");tile(c,2,sb,0xff858585.toInt(),if(pause)"▶"else"Ⅱ",if(pause)"play"else"pause");tile(c,3,sb,0xff858585.toInt(),"ER","eraser",eraser);tile(c,4,sb,0xff79dcf3.toInt(),"°C","heat",view==1);tile(c,5,sb,0xffffff83.toInt(),"⚡","electric",view==2)}
 private fun bg(d:D)=when{d.id==ANT||d.id==SEED->0xffb9e98f.toInt();d.cond->0xffd7c4ff.toInt();d.state==2||d.id==ICE||d.id==SNOW||d.id==NITROGEN->0xff81def3.toInt();d.flam||d.id==FIRE||d.id==LAVA||d.id==PLASMA->0xfffff287.toInt();d.state==3->0xffd8e1e5.toInt();else->0xfff4f4f4.toInt()}
 private fun elements(c:Canvas){val top=sb+th;val max=max(0f,ceil(menu.size/6.0).toFloat()*th-(height-top));scroll=scroll.coerceIn(0f,max);for(n in menu.indices){val r=n/6;val col=n%6;val y=top+r*th-scroll;if(y+th<top||y>height)continue;val d=menu[n];tile(c,col,y,bg(d),d.s,d.n,d.id==sel&&!eraser)}}
 override fun onTouchEvent(e:MotionEvent):Boolean{val x=e.x;val y=e.y;when(e.actionMasked){MotionEvent.ACTION_DOWN->{lx=x;ly=y;if(y<sb){world=true;panel=false;paintAt(x,y)}else{world=false;panel=true;py=y}};MotionEvent.ACTION_MOVE->{if(world){paintLine(lx,ly,x,y);lx=x;ly=y}else if(panel&&y>sb+th){scroll-=y-py;py=y;invalidate()}};MotionEvent.ACTION_UP->{if(panel&&abs(y-ly)<24)tap(x,y);world=false;panel=false;performClick();invalidate()};MotionEvent.ACTION_CANCEL->{world=false;panel=false}};return true};override fun performClick():Boolean{super.performClick();return true}
 private fun tap(x:Float,y:Float){val col=(x/tw).toInt().coerceIn(0,5);if(y<sb+th){when(col){0->newWorld();1->view=(view+1)%3;2->pause=!pause;3->eraser=!eraser;4->view=1;5->view=2};return};val n=(((y-(sb+th)+scroll)/th).toInt()*6)+col;if(n in menu.indices){sel=menu[n].id;eraser=false}}
 private fun paintAt(px:Float,pyy:Float){val cx=(px/width*W).toInt().coerceIn(0,W-1);val cy=(pyy/sb*H).toInt().coerceIn(0,H-1);val e=if(eraser)AIR else sel;val b=4;for(dy in-b..b)for(dx in-b..b)if(dx*dx+dy*dy<=b*b&&inside(cx+dx,cy+dy)){val i=id(cx+dx,cy+dy);if(e==AIR)clear(i)else if((g[i].toInt()and255)==AIR||ds[e]?.state==0||e==FIRE||e==SPARK||e==PLASMA)set(cx+dx,cy+dy,e)}}
 private fun paintLine(x0:Float,y0:Float,x1:Float,y1:Float){val n=max(1,(max(abs(x1-x0),abs(y1-y0))/10).toInt());for(k in 0..n){val f=k.toFloat()/n;paintAt(x0+(x1-x0)*f,y0+(y1-y0)*f)}}
 private fun newWorld(){java.util.Arrays.fill(g,0);java.util.Arrays.fill(life,0);java.util.Arrays.fill(v,0f);java.util.Arrays.fill(t,20f);for(x in 0 until W)set(x,H-1,STONE)}
 private fun demo(){newWorld();for(x in 10..45)for(y in 200 until H-1)if(rnd.nextFloat()<.72)set(x,y,SAND);for(x in 58..96)for(y in 208 until H-1)if(rnd.nextFloat()<.72)set(x,y,WATER);for(x in 110..138)set(x,214,WOOD);for(x in 116..132)for(y in 215 until H-1)if(rnd.nextFloat()<.5)set(x,y,OIL);for(x in 145..156)for(y in 220 until H-1)if(rnd.nextFloat()<.65)set(x,y,LAVA);for(x in 18..28)set(x,197,SEED);for(x in 72..80)set(x,202,NITROGEN);for(x in 32..38)set(x,196,ANT);for(x in 104..108)set(x,190,BATTERY);for(x in 109..130)set(x,190,WIRE);set(131,190,LAMP)}
}
