(function(){
'use strict';

const API='https://api.groq.com/openai/v1/chat/completions';
const TEXT_FAST='openai/gpt-oss-20b';
const TEXT_SMART='openai/gpt-oss-120b';
const VISION='qwen/qwen3.6-27b';
const PDFJS_URL='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs';
const PDFJS_WORKER='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';
const LANGS={de:'Deutsch',en:'English',fr:'Français',es:'Español',it:'Italiano',nl:'Nederlands',pl:'Polski',tr:'Türkçe',pt:'Português',ru:'Русский',ja:'日本語',ko:'한국어',zh:'中文'};
const SPEECH_LANG={de:'de-DE',en:'en-US',fr:'fr-FR',es:'es-ES',it:'it-IT',nl:'nl-NL',pl:'pl-PL',tr:'tr-TR',pt:'pt-PT',ru:'ru-RU',ja:'ja-JP',ko:'ko-KR',zh:'zh-CN'};

const EXTRA={
  en:{search:'Search chats',memory:'Memory',settings:'Appearance',installApp:'Install app',usage:'Usage',attachImage:'Add image',attachFile:'Add file',edit:'Edit',regenerate:'Regenerate',like:'Helpful',dislike:'Not helpful',speak:'Read aloud',rememberThis:'Remember this',pin:'Pin',unpin:'Unpin',memoryTitle:'Sliqadius Memory',memoryHint:'Saved locally and added to future prompts. Only add things you want Sliqadius to remember.',memoryPlaceholder:'What should Sliqadius remember?',addMemory:'Add memory',noMemories:'No saved memories yet.',remove:'Remove',appearanceTitle:'Appearance',themeSystem:'System',themeDark:'Dark',themeLight:'Light',usageTitle:'API usage',requests:'Requests',tokens:'Tokens',inputTokens:'Input',outputTokens:'Output',remainingRequests:'Requests remaining',remainingTokens:'Tokens remaining',requestReset:'Request reset',tokenReset:'Token reset',lastModel:'Last model',clear:'Clear stats',stop:'Stop',send:'Send',mic:'Voice input',micUnavailable:'Voice input is not supported by this browser.',fileAdded:'File added',fileTooLarge:'This file is too large.',unsupportedFile:'This file type is not supported.',pdfFailed:'The PDF could not be read.',maxAttachments:'Maximum 5 attachments per message.',editTitle:'Edit message',saveRegenerate:'Save & regenerate',installUnavailable:'Your browser does not currently offer direct app installation.',installed:'Sliqadius is already installed.',feedbackSaved:'Feedback saved locally.',streamStopped:'Generation stopped.',apiKeyChanged:'API key saved. The matching local chat library was loaded.',storageError:'Local storage is full. Export a backup or remove large chats/files.',files:'Files',appearance:'Appearance',pinned:'Pinned',notAvailable:'Not available',estimated:'estimated',code:'Code',copyCode:'Copy code',localOnly:'Stored locally on this device',noRateData:'No rate-limit data yet.'},
  de:{search:'Chats durchsuchen',memory:'Memory',settings:'Darstellung',installApp:'App installieren',usage:'Nutzung',attachImage:'Bild hinzufügen',attachFile:'Datei hinzufügen',edit:'Bearbeiten',regenerate:'Neu generieren',like:'Hilfreich',dislike:'Nicht hilfreich',speak:'Vorlesen',rememberThis:'Merken',pin:'Anpinnen',unpin:'Loslösen',memoryTitle:'Sliqadius Memory',memoryHint:'Wird lokal gespeichert und zukünftigen Anfragen hinzugefügt. Speichere nur Dinge, die Sliqadius wirklich merken soll.',memoryPlaceholder:'Was soll Sliqadius sich merken?',addMemory:'Memory hinzufügen',noMemories:'Noch keine Erinnerungen gespeichert.',remove:'Entfernen',appearanceTitle:'Darstellung',themeSystem:'System',themeDark:'Dunkel',themeLight:'Hell',usageTitle:'API-Nutzung',requests:'Anfragen',tokens:'Tokens',inputTokens:'Eingabe',outputTokens:'Ausgabe',remainingRequests:'Verbleibende Anfragen',remainingTokens:'Verbleibende Tokens',requestReset:'Anfragen-Reset',tokenReset:'Token-Reset',lastModel:'Letztes Modell',clear:'Statistik löschen',stop:'Stoppen',send:'Senden',mic:'Spracheingabe',micUnavailable:'Spracheingabe wird von diesem Browser nicht unterstützt.',fileAdded:'Datei hinzugefügt',fileTooLarge:'Diese Datei ist zu groß.',unsupportedFile:'Dieser Dateityp wird nicht unterstützt.',pdfFailed:'Die PDF konnte nicht gelesen werden.',maxAttachments:'Maximal 5 Anhänge pro Nachricht.',editTitle:'Nachricht bearbeiten',saveRegenerate:'Speichern & neu generieren',installUnavailable:'Dein Browser bietet die direkte App-Installation gerade nicht an.',installed:'Sliqadius ist bereits installiert.',feedbackSaved:'Feedback lokal gespeichert.',streamStopped:'Generierung gestoppt.',apiKeyChanged:'API-Key gespeichert. Die passende lokale Chat-Bibliothek wurde geladen.',storageError:'Der lokale Speicher ist voll. Sichere deine Daten oder entferne große Chats/Dateien.',files:'Dateien',appearance:'Darstellung',pinned:'Angepinnt',notAvailable:'Nicht verfügbar',estimated:'geschätzt',code:'Code',copyCode:'Code kopieren',localOnly:'Lokal auf diesem Gerät gespeichert',noRateData:'Noch keine Rate-Limit-Daten.'},
  fr:{search:'Rechercher des chats',memory:'Mémoire',settings:'Apparence',installApp:"Installer l’app",usage:'Utilisation',attachImage:'Ajouter une image',attachFile:'Ajouter un fichier',edit:'Modifier',regenerate:'Régénérer',like:'Utile',dislike:'Pas utile',speak:'Lire à voix haute',rememberThis:'Mémoriser',pin:'Épingler',unpin:'Désépingler',memoryTitle:'Mémoire Sliqadius',memoryHint:'Enregistrée localement et ajoutée aux futures requêtes.',memoryPlaceholder:'Que doit mémoriser Sliqadius ?',addMemory:'Ajouter',noMemories:'Aucun souvenir enregistré.',remove:'Supprimer',appearanceTitle:'Apparence',themeSystem:'Système',themeDark:'Sombre',themeLight:'Clair',usageTitle:'Utilisation API',requests:'Requêtes',tokens:'Tokens',inputTokens:'Entrée',outputTokens:'Sortie',remainingRequests:'Requêtes restantes',remainingTokens:'Tokens restants',requestReset:'Réinitialisation requêtes',tokenReset:'Réinitialisation tokens',lastModel:'Dernier modèle',clear:'Effacer les stats',stop:'Arrêter',send:'Envoyer',mic:'Saisie vocale',micUnavailable:"La saisie vocale n’est pas prise en charge.",fileAdded:'Fichier ajouté',fileTooLarge:'Ce fichier est trop volumineux.',unsupportedFile:'Type de fichier non pris en charge.',pdfFailed:'Impossible de lire le PDF.',maxAttachments:'Maximum 5 pièces jointes.',editTitle:'Modifier le message',saveRegenerate:'Enregistrer et régénérer',installUnavailable:"L’installation directe n’est pas disponible.",installed:'Sliqadius est déjà installé.',feedbackSaved:'Avis enregistré localement.',streamStopped:'Génération arrêtée.',apiKeyChanged:'Clé API enregistrée. Les chats locaux correspondants ont été chargés.',storageError:'Le stockage local est plein.',files:'Fichiers',appearance:'Apparence',pinned:'Épinglé',notAvailable:'Indisponible',estimated:'estimé',code:'Code',copyCode:'Copier le code',localOnly:'Enregistré localement',noRateData:'Aucune donnée de limite.'},
  es:{search:'Buscar chats',memory:'Memoria',settings:'Apariencia',installApp:'Instalar app',usage:'Uso',attachImage:'Añadir imagen',attachFile:'Añadir archivo',edit:'Editar',regenerate:'Regenerar',like:'Útil',dislike:'No útil',speak:'Leer en voz alta',rememberThis:'Recordar',pin:'Fijar',unpin:'Desfijar',memoryTitle:'Memoria de Sliqadius',memoryHint:'Se guarda localmente y se añade a futuras consultas.',memoryPlaceholder:'¿Qué debe recordar Sliqadius?',addMemory:'Añadir memoria',noMemories:'Aún no hay recuerdos guardados.',remove:'Eliminar',appearanceTitle:'Apariencia',themeSystem:'Sistema',themeDark:'Oscuro',themeLight:'Claro',usageTitle:'Uso de API',requests:'Solicitudes',tokens:'Tokens',inputTokens:'Entrada',outputTokens:'Salida',remainingRequests:'Solicitudes restantes',remainingTokens:'Tokens restantes',requestReset:'Reinicio de solicitudes',tokenReset:'Reinicio de tokens',lastModel:'Último modelo',clear:'Borrar estadísticas',stop:'Detener',send:'Enviar',mic:'Entrada de voz',micUnavailable:'La entrada de voz no es compatible con este navegador.',fileAdded:'Archivo añadido',fileTooLarge:'Este archivo es demasiado grande.',unsupportedFile:'Tipo de archivo no compatible.',pdfFailed:'No se pudo leer el PDF.',maxAttachments:'Máximo 5 archivos por mensaje.',editTitle:'Editar mensaje',saveRegenerate:'Guardar y regenerar',installUnavailable:'Tu navegador no ofrece instalación directa ahora.',installed:'Sliqadius ya está instalado.',feedbackSaved:'Opinión guardada localmente.',streamStopped:'Generación detenida.',apiKeyChanged:'Clave API guardada. Se cargaron los chats locales correspondientes.',storageError:'El almacenamiento local está lleno.',files:'Archivos',appearance:'Apariencia',pinned:'Fijado',notAvailable:'No disponible',estimated:'estimado',code:'Código',copyCode:'Copiar código',localOnly:'Guardado localmente',noRateData:'Aún no hay datos de límites.'},
  it:{search:'Cerca chat',memory:'Memoria',settings:'Aspetto',installApp:'Installa app',usage:'Utilizzo',attachImage:'Aggiungi immagine',attachFile:'Aggiungi file',edit:'Modifica',regenerate:'Rigenera',like:'Utile',dislike:'Non utile',speak:'Leggi ad alta voce',rememberThis:'Ricorda',pin:'Fissa',unpin:'Rimuovi fissaggio',memoryTitle:'Memoria Sliqadius',memoryHint:'Salvata localmente e aggiunta alle richieste future.',memoryPlaceholder:'Cosa deve ricordare Sliqadius?',addMemory:'Aggiungi memoria',noMemories:'Nessun ricordo salvato.',remove:'Rimuovi',appearanceTitle:'Aspetto',themeSystem:'Sistema',themeDark:'Scuro',themeLight:'Chiaro',usageTitle:'Utilizzo API',requests:'Richieste',tokens:'Token',inputTokens:'Input',outputTokens:'Output',remainingRequests:'Richieste rimanenti',remainingTokens:'Token rimanenti',requestReset:'Reset richieste',tokenReset:'Reset token',lastModel:'Ultimo modello',clear:'Azzera statistiche',stop:'Interrompi',send:'Invia',mic:'Input vocale',micUnavailable:'Input vocale non supportato.',fileAdded:'File aggiunto',fileTooLarge:'File troppo grande.',unsupportedFile:'Tipo di file non supportato.',pdfFailed:'Impossibile leggere il PDF.',maxAttachments:'Massimo 5 allegati.',editTitle:'Modifica messaggio',saveRegenerate:'Salva e rigenera',installUnavailable:'Installazione diretta non disponibile.',installed:'Sliqadius è già installato.',feedbackSaved:'Feedback salvato localmente.',streamStopped:'Generazione interrotta.',apiKeyChanged:'API key salvata. Chat locali corrispondenti caricate.',storageError:'Memoria locale piena.',files:'File',appearance:'Aspetto',pinned:'Fissato',notAvailable:'Non disponibile',estimated:'stimato',code:'Codice',copyCode:'Copia codice',localOnly:'Salvato localmente',noRateData:'Nessun dato sui limiti.'},
  nl:{search:'Chats zoeken',memory:'Geheugen',settings:'Weergave',installApp:'App installeren',usage:'Gebruik',attachImage:'Afbeelding toevoegen',attachFile:'Bestand toevoegen',edit:'Bewerken',regenerate:'Opnieuw genereren',like:'Nuttig',dislike:'Niet nuttig',speak:'Voorlezen',rememberThis:'Onthouden',pin:'Vastmaken',unpin:'Losmaken',memoryTitle:'Sliqadius-geheugen',memoryHint:'Wordt lokaal opgeslagen en aan toekomstige vragen toegevoegd.',memoryPlaceholder:'Wat moet Sliqadius onthouden?',addMemory:'Toevoegen',noMemories:'Nog geen herinneringen.',remove:'Verwijderen',appearanceTitle:'Weergave',themeSystem:'Systeem',themeDark:'Donker',themeLight:'Licht',usageTitle:'API-gebruik',requests:'Verzoeken',tokens:'Tokens',inputTokens:'Invoer',outputTokens:'Uitvoer',remainingRequests:'Resterende verzoeken',remainingTokens:'Resterende tokens',requestReset:'Reset verzoeken',tokenReset:'Reset tokens',lastModel:'Laatste model',clear:'Statistieken wissen',stop:'Stoppen',send:'Verzenden',mic:'Spraakinvoer',micUnavailable:'Spraakinvoer wordt niet ondersteund.',fileAdded:'Bestand toegevoegd',fileTooLarge:'Bestand is te groot.',unsupportedFile:'Bestandstype niet ondersteund.',pdfFailed:'PDF kon niet worden gelezen.',maxAttachments:'Maximaal 5 bijlagen.',editTitle:'Bericht bewerken',saveRegenerate:'Opslaan en opnieuw genereren',installUnavailable:'Direct installeren is niet beschikbaar.',installed:'Sliqadius is al geïnstalleerd.',feedbackSaved:'Feedback lokaal opgeslagen.',streamStopped:'Genereren gestopt.',apiKeyChanged:'API-key opgeslagen. Bijbehorende lokale chats geladen.',storageError:'Lokale opslag is vol.',files:'Bestanden',appearance:'Weergave',pinned:'Vastgemaakt',notAvailable:'Niet beschikbaar',estimated:'geschat',code:'Code',copyCode:'Code kopiëren',localOnly:'Lokaal opgeslagen',noRateData:'Nog geen limietgegevens.'},
  pl:{search:'Szukaj czatów',memory:'Pamięć',settings:'Wygląd',installApp:'Zainstaluj aplikację',usage:'Użycie',attachImage:'Dodaj obraz',attachFile:'Dodaj plik',edit:'Edytuj',regenerate:'Wygeneruj ponownie',like:'Pomocne',dislike:'Niepomocne',speak:'Czytaj na głos',rememberThis:'Zapamiętaj',pin:'Przypnij',unpin:'Odepnij',memoryTitle:'Pamięć Sliqadius',memoryHint:'Zapisywana lokalnie i dodawana do przyszłych zapytań.',memoryPlaceholder:'Co Sliqadius ma zapamiętać?',addMemory:'Dodaj',noMemories:'Brak zapisanych wspomnień.',remove:'Usuń',appearanceTitle:'Wygląd',themeSystem:'System',themeDark:'Ciemny',themeLight:'Jasny',usageTitle:'Użycie API',requests:'Żądania',tokens:'Tokeny',inputTokens:'Wejście',outputTokens:'Wyjście',remainingRequests:'Pozostałe żądania',remainingTokens:'Pozostałe tokeny',requestReset:'Reset żądań',tokenReset:'Reset tokenów',lastModel:'Ostatni model',clear:'Wyczyść statystyki',stop:'Zatrzymaj',send:'Wyślij',mic:'Wprowadzanie głosowe',micUnavailable:'Wprowadzanie głosowe nie jest obsługiwane.',fileAdded:'Dodano plik',fileTooLarge:'Plik jest za duży.',unsupportedFile:'Nieobsługiwany typ pliku.',pdfFailed:'Nie udało się odczytać PDF.',maxAttachments:'Maksymalnie 5 załączników.',editTitle:'Edytuj wiadomość',saveRegenerate:'Zapisz i wygeneruj ponownie',installUnavailable:'Instalacja bezpośrednia jest niedostępna.',installed:'Sliqadius jest już zainstalowany.',feedbackSaved:'Opinię zapisano lokalnie.',streamStopped:'Generowanie zatrzymane.',apiKeyChanged:'Klucz API zapisany. Wczytano powiązane lokalne czaty.',storageError:'Pamięć lokalna jest pełna.',files:'Pliki',appearance:'Wygląd',pinned:'Przypięty',notAvailable:'Niedostępne',estimated:'szacowane',code:'Kod',copyCode:'Kopiuj kod',localOnly:'Zapisano lokalnie',noRateData:'Brak danych limitów.'},
  tr:{search:'Sohbetlerde ara',memory:'Hafıza',settings:'Görünüm',installApp:'Uygulamayı yükle',usage:'Kullanım',attachImage:'Görsel ekle',attachFile:'Dosya ekle',edit:'Düzenle',regenerate:'Yeniden oluştur',like:'Yararlı',dislike:'Yararlı değil',speak:'Sesli oku',rememberThis:'Hatırla',pin:'Sabitle',unpin:'Sabitlemeyi kaldır',memoryTitle:'Sliqadius Hafızası',memoryHint:'Yerel olarak kaydedilir ve gelecekteki isteklere eklenir.',memoryPlaceholder:'Sliqadius neyi hatırlasın?',addMemory:'Hafızaya ekle',noMemories:'Henüz kayıtlı hafıza yok.',remove:'Kaldır',appearanceTitle:'Görünüm',themeSystem:'Sistem',themeDark:'Koyu',themeLight:'Açık',usageTitle:'API kullanımı',requests:'İstekler',tokens:'Tokenlar',inputTokens:'Girdi',outputTokens:'Çıktı',remainingRequests:'Kalan istekler',remainingTokens:'Kalan tokenlar',requestReset:'İstek sıfırlama',tokenReset:'Token sıfırlama',lastModel:'Son model',clear:'İstatistikleri temizle',stop:'Durdur',send:'Gönder',mic:'Sesli giriş',micUnavailable:'Sesli giriş bu tarayıcıda desteklenmiyor.',fileAdded:'Dosya eklendi',fileTooLarge:'Dosya çok büyük.',unsupportedFile:'Dosya türü desteklenmiyor.',pdfFailed:'PDF okunamadı.',maxAttachments:'En fazla 5 ek.',editTitle:'Mesajı düzenle',saveRegenerate:'Kaydet ve yeniden oluştur',installUnavailable:'Doğrudan yükleme şu anda kullanılamıyor.',installed:'Sliqadius zaten yüklü.',feedbackSaved:'Geri bildirim yerel olarak kaydedildi.',streamStopped:'Oluşturma durduruldu.',apiKeyChanged:'API anahtarı kaydedildi. Eşleşen yerel sohbetler yüklendi.',storageError:'Yerel depolama dolu.',files:'Dosyalar',appearance:'Görünüm',pinned:'Sabitlendi',notAvailable:'Kullanılamıyor',estimated:'tahmini',code:'Kod',copyCode:'Kodu kopyala',localOnly:'Yerel olarak kaydedildi',noRateData:'Henüz limit verisi yok.'},
  pt:{search:'Pesquisar chats',memory:'Memória',settings:'Aparência',installApp:'Instalar app',usage:'Utilização',attachImage:'Adicionar imagem',attachFile:'Adicionar ficheiro',edit:'Editar',regenerate:'Gerar novamente',like:'Útil',dislike:'Não útil',speak:'Ler em voz alta',rememberThis:'Lembrar',pin:'Fixar',unpin:'Desafixar',memoryTitle:'Memória Sliqadius',memoryHint:'Guardada localmente e adicionada a pedidos futuros.',memoryPlaceholder:'O que o Sliqadius deve lembrar?',addMemory:'Adicionar memória',noMemories:'Ainda não há memórias guardadas.',remove:'Remover',appearanceTitle:'Aparência',themeSystem:'Sistema',themeDark:'Escuro',themeLight:'Claro',usageTitle:'Utilização da API',requests:'Pedidos',tokens:'Tokens',inputTokens:'Entrada',outputTokens:'Saída',remainingRequests:'Pedidos restantes',remainingTokens:'Tokens restantes',requestReset:'Reset de pedidos',tokenReset:'Reset de tokens',lastModel:'Último modelo',clear:'Limpar estatísticas',stop:'Parar',send:'Enviar',mic:'Entrada de voz',micUnavailable:'Entrada de voz não suportada.',fileAdded:'Ficheiro adicionado',fileTooLarge:'Ficheiro demasiado grande.',unsupportedFile:'Tipo de ficheiro não suportado.',pdfFailed:'Não foi possível ler o PDF.',maxAttachments:'Máximo de 5 anexos.',editTitle:'Editar mensagem',saveRegenerate:'Guardar e gerar novamente',installUnavailable:'A instalação direta não está disponível.',installed:'Sliqadius já está instalado.',feedbackSaved:'Feedback guardado localmente.',streamStopped:'Geração parada.',apiKeyChanged:'Chave API guardada. Chats locais correspondentes carregados.',storageError:'O armazenamento local está cheio.',files:'Ficheiros',appearance:'Aparência',pinned:'Fixado',notAvailable:'Indisponível',estimated:'estimado',code:'Código',copyCode:'Copiar código',localOnly:'Guardado localmente',noRateData:'Ainda não há dados de limites.'},
  ru:{search:'Поиск чатов',memory:'Память',settings:'Оформление',installApp:'Установить приложение',usage:'Использование',attachImage:'Добавить изображение',attachFile:'Добавить файл',edit:'Изменить',regenerate:'Сгенерировать заново',like:'Полезно',dislike:'Не полезно',speak:'Прочитать вслух',rememberThis:'Запомнить',pin:'Закрепить',unpin:'Открепить',memoryTitle:'Память Sliqadius',memoryHint:'Хранится локально и добавляется к будущим запросам.',memoryPlaceholder:'Что Sliqadius должен запомнить?',addMemory:'Добавить',noMemories:'Сохранённых воспоминаний пока нет.',remove:'Удалить',appearanceTitle:'Оформление',themeSystem:'Система',themeDark:'Тёмная',themeLight:'Светлая',usageTitle:'Использование API',requests:'Запросы',tokens:'Токены',inputTokens:'Ввод',outputTokens:'Вывод',remainingRequests:'Осталось запросов',remainingTokens:'Осталось токенов',requestReset:'Сброс запросов',tokenReset:'Сброс токенов',lastModel:'Последняя модель',clear:'Очистить статистику',stop:'Остановить',send:'Отправить',mic:'Голосовой ввод',micUnavailable:'Голосовой ввод не поддерживается.',fileAdded:'Файл добавлен',fileTooLarge:'Файл слишком большой.',unsupportedFile:'Тип файла не поддерживается.',pdfFailed:'Не удалось прочитать PDF.',maxAttachments:'Не более 5 вложений.',editTitle:'Изменить сообщение',saveRegenerate:'Сохранить и сгенерировать заново',installUnavailable:'Прямая установка сейчас недоступна.',installed:'Sliqadius уже установлен.',feedbackSaved:'Оценка сохранена локально.',streamStopped:'Генерация остановлена.',apiKeyChanged:'API-ключ сохранён. Загружены соответствующие локальные чаты.',storageError:'Локальное хранилище заполнено.',files:'Файлы',appearance:'Оформление',pinned:'Закреплено',notAvailable:'Недоступно',estimated:'примерно',code:'Код',copyCode:'Копировать код',localOnly:'Сохранено локально',noRateData:'Данных о лимитах пока нет.'},
  ja:{search:'チャットを検索',memory:'メモリ',settings:'外観',installApp:'アプリをインストール',usage:'使用量',attachImage:'画像を追加',attachFile:'ファイルを追加',edit:'編集',regenerate:'再生成',like:'役に立った',dislike:'役に立たなかった',speak:'読み上げ',rememberThis:'記憶する',pin:'固定',unpin:'固定解除',memoryTitle:'Sliqadius メモリ',memoryHint:'ローカルに保存され、今後のリクエストに追加されます。',memoryPlaceholder:'Sliqadius に何を覚えさせますか？',addMemory:'メモリを追加',noMemories:'保存されたメモリはありません。',remove:'削除',appearanceTitle:'外観',themeSystem:'システム',themeDark:'ダーク',themeLight:'ライト',usageTitle:'API 使用量',requests:'リクエスト',tokens:'トークン',inputTokens:'入力',outputTokens:'出力',remainingRequests:'残りリクエスト',remainingTokens:'残りトークン',requestReset:'リクエストリセット',tokenReset:'トークンリセット',lastModel:'最後のモデル',clear:'統計を消去',stop:'停止',send:'送信',mic:'音声入力',micUnavailable:'このブラウザは音声入力に対応していません。',fileAdded:'ファイルを追加しました',fileTooLarge:'ファイルが大きすぎます。',unsupportedFile:'このファイル形式は未対応です。',pdfFailed:'PDFを読み取れませんでした。',maxAttachments:'添付は最大5個です。',editTitle:'メッセージを編集',saveRegenerate:'保存して再生成',installUnavailable:'現在、直接インストールできません。',installed:'Sliqadius はすでにインストールされています。',feedbackSaved:'評価をローカル保存しました。',streamStopped:'生成を停止しました。',apiKeyChanged:'APIキーを保存し、対応するローカルチャットを読み込みました。',storageError:'ローカルストレージがいっぱいです。',files:'ファイル',appearance:'外観',pinned:'固定済み',notAvailable:'利用不可',estimated:'推定',code:'コード',copyCode:'コードをコピー',localOnly:'この端末にローカル保存',noRateData:'レート制限データはまだありません。'},
  ko:{search:'채팅 검색',memory:'메모리',settings:'화면 설정',installApp:'앱 설치',usage:'사용량',attachImage:'이미지 추가',attachFile:'파일 추가',edit:'편집',regenerate:'다시 생성',like:'도움됨',dislike:'도움 안 됨',speak:'소리 내어 읽기',rememberThis:'기억하기',pin:'고정',unpin:'고정 해제',memoryTitle:'Sliqadius 메모리',memoryHint:'로컬에 저장되고 이후 요청에 추가됩니다.',memoryPlaceholder:'Sliqadius가 무엇을 기억해야 하나요?',addMemory:'메모리 추가',noMemories:'저장된 메모리가 없습니다.',remove:'삭제',appearanceTitle:'화면 설정',themeSystem:'시스템',themeDark:'다크',themeLight:'라이트',usageTitle:'API 사용량',requests:'요청',tokens:'토큰',inputTokens:'입력',outputTokens:'출력',remainingRequests:'남은 요청',remainingTokens:'남은 토큰',requestReset:'요청 리셋',tokenReset:'토큰 리셋',lastModel:'마지막 모델',clear:'통계 지우기',stop:'중지',send:'보내기',mic:'음성 입력',micUnavailable:'이 브라우저는 음성 입력을 지원하지 않습니다.',fileAdded:'파일 추가됨',fileTooLarge:'파일이 너무 큽니다.',unsupportedFile:'지원하지 않는 파일 형식입니다.',pdfFailed:'PDF를 읽을 수 없습니다.',maxAttachments:'첨부는 최대 5개입니다.',editTitle:'메시지 편집',saveRegenerate:'저장 후 다시 생성',installUnavailable:'현재 직접 설치를 지원하지 않습니다.',installed:'Sliqadius가 이미 설치되어 있습니다.',feedbackSaved:'피드백을 로컬에 저장했습니다.',streamStopped:'생성을 중지했습니다.',apiKeyChanged:'API 키를 저장하고 해당 로컬 채팅을 불러왔습니다.',storageError:'로컬 저장 공간이 가득 찼습니다.',files:'파일',appearance:'화면 설정',pinned:'고정됨',notAvailable:'사용 불가',estimated:'추정',code:'코드',copyCode:'코드 복사',localOnly:'이 기기에 로컬 저장',noRateData:'아직 제한 데이터가 없습니다.'},
  zh:{search:'搜索聊天',memory:'记忆',settings:'外观',installApp:'安装应用',usage:'用量',attachImage:'添加图片',attachFile:'添加文件',edit:'编辑',regenerate:'重新生成',like:'有帮助',dislike:'没帮助',speak:'朗读',rememberThis:'记住',pin:'置顶',unpin:'取消置顶',memoryTitle:'Sliqadius 记忆',memoryHint:'保存在本机，并加入之后的请求。',memoryPlaceholder:'Sliqadius 应该记住什么？',addMemory:'添加记忆',noMemories:'还没有保存的记忆。',remove:'删除',appearanceTitle:'外观',themeSystem:'跟随系统',themeDark:'深色',themeLight:'浅色',usageTitle:'API 用量',requests:'请求',tokens:'Token',inputTokens:'输入',outputTokens:'输出',remainingRequests:'剩余请求',remainingTokens:'剩余 Token',requestReset:'请求重置',tokenReset:'Token 重置',lastModel:'上次模型',clear:'清除统计',stop:'停止',send:'发送',mic:'语音输入',micUnavailable:'此浏览器不支持语音输入。',fileAdded:'已添加文件',fileTooLarge:'文件太大。',unsupportedFile:'不支持此文件类型。',pdfFailed:'无法读取 PDF。',maxAttachments:'每条消息最多 5 个附件。',editTitle:'编辑消息',saveRegenerate:'保存并重新生成',installUnavailable:'当前浏览器暂不提供直接安装。',installed:'Sliqadius 已安装。',feedbackSaved:'反馈已保存在本机。',streamStopped:'已停止生成。',apiKeyChanged:'API Key 已保存，并加载了对应的本地聊天。',storageError:'本地存储空间已满。',files:'文件',appearance:'外观',pinned:'已置顶',notAvailable:'不可用',estimated:'估算',code:'代码',copyCode:'复制代码',localOnly:'保存在此设备本机',noRateData:'暂无速率限制数据。'}
};

const FALLBACK={newChat:'＋ New Chat',changeKey:'Change API key',placeholder:'Message Sliqadius',welcome:'How can I help you?',hint:'Write a message, paste an image, or attach a file.',thinking:'Sliqadius is thinking',language:'Language',install:'Installation guide',back:'← Back to website',note:'Enter = send · Shift + Enter = new line',fast:'Fast',medium:'Medium',smart:'Smart',apiMissing:'API missing',apiReady:'API ready',keyText:'Sliqadius needs a Groq API key to send messages.',keyHint:'The API key and chats stay saved locally on this device.',keyRequired:'Please add a Groq API key first.',cancel:'Cancel',save:'Save',getKey:'Get API key',invalid:'Please enter a valid Groq API key.',image:'Image selected',imageQ:'What is shown in this image?',error:'Something went wrong. Please try again.',network:'Groq could not be reached. Check your connection, HTTPS and API key.',unauth:'The API key is invalid or expired.',limit:'The Groq limit has been reached. Try again later.',backup:'Back up data',restore:'Restore backup',saved:'Saved automatically',copy:'Copy',copied:'Copied',rename:'Rename',del:'Delete',renameTitle:'Rename chat',backupDone:'Backup created',restoreDone:'Backup restored',confirmDelete:'Delete this chat?',suggest1:'Explain something',suggest2:'Help me code',suggest3:'Analyze a file'};

const $=id=>document.getElementById(id);
function lsGet(k,d=''){try{const v=localStorage.getItem(k);return v===null?d:v}catch(e){return d}}
function lsSet(k,v){try{localStorage.setItem(k,v);return true}catch(e){return false}}
function uid(prefix='x'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9)}
function normLang(x){x=String(x||'').slice(0,2).toLowerCase();return LANGS[x]?x:'en'}
function hashKey(key){key=String(key||'guest');let h1=2166136261>>>0,h2=2246822519>>>0;for(let i=0;i<key.length;i++){const c=key.charCodeAt(i);h1^=c;h1=Math.imul(h1,16777619)>>>0;h2^=(c+i*31);h2=Math.imul(h2,3266489917)>>>0}return h1.toString(36)+h2.toString(36)}
function stateKey(key){return 'state:'+hashKey(key||'guest')}
function clone(v){return JSON.parse(JSON.stringify(v))}

let DB=null;
function openDb(){return new Promise(resolve=>{if(!indexedDB){resolve(null);return}const r=indexedDB.open('sliqadius-web-v15',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onsuccess=()=>{DB=r.result;resolve(DB)};r.onerror=()=>resolve(null)})}
function dbGet(k){return new Promise(resolve=>{if(!DB){resolve(null);return}try{const r=DB.transaction('kv','readonly').objectStore('kv').get(k);r.onsuccess=()=>resolve(r.result===undefined?null:r.result);r.onerror=()=>resolve(null)}catch(e){resolve(null)}})}
function dbPut(k,v){return new Promise(resolve=>{if(!DB){resolve(false);return}try{const tx=DB.transaction('kv','readwrite');tx.objectStore('kv').put(v,k);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false)}catch(e){resolve(false)}})}

let lang=normLang(lsGet('sliq-web-lang',navigator.language||'en'));
let ui=Object.assign({},FALLBACK,EXTRA[lang]||EXTRA.en);
let mode=['fast','medium','smart'].includes(lsGet('sliq-web-mode','medium'))?lsGet('sliq-web-mode','medium'):'medium';
let theme=lsGet('sliq-v15-theme','system');
let apiKey=lsGet('sliq-web-key','');
let state=null;
let current='';
let pending=[];
let busy=false;
let activeController=null;
let stopping=false;
let retryAfterKey=false;
let renameId=null;
let editId=null;
let saveTimer=null;
let searchTerm='';
let recognition=null;
let recognitionBase='';
let deferredInstall=null;
let pdfModulePromise=null;
let storageWarned=false;

function defaultState(){return{version:15,chats:[],memories:[],usage:{requests:0,totalTokens:0,inputTokens:0,outputTokens:0,estimated:true,lastModel:'',rate:{}},current:''}}
function blankChat(){return{id:uid('c'),title:(ui.newChat||'New Chat').replace(/^＋\s*/,''),messages:[],updated:Date.now(),pinned:false}}
function normalizeMessage(m){return{id:m.id||uid('m'),role:m.role==='assistant'?'assistant':'user',content:String(m.content||''),attachments:Array.isArray(m.attachments)?m.attachments:((m.image)?[{id:uid('a'),kind:'image',name:'image',mime:'image/jpeg',thumb:m.image,data:m.image}]:[]),feedback:m.feedback||null,created:m.created||Date.now(),streaming:false}}
function normalizeState(s){s=s&&typeof s==='object'?s:defaultState();s.version=15;s.memories=Array.isArray(s.memories)?s.memories.map(x=>({id:x.id||uid('mem'),text:String(x.text||x).slice(0,500),created:x.created||Date.now()})).filter(x=>x.text.trim()):[];s.usage=Object.assign(defaultState().usage,s.usage||{});s.usage.rate=s.usage.rate||{};s.chats=Array.isArray(s.chats)?s.chats.map(c=>({id:c.id||uid('c'),title:String(c.title||'Chat').slice(0,80),messages:Array.isArray(c.messages)?c.messages.map(normalizeMessage):[],updated:Number(c.updated||Date.now()),pinned:!!c.pinned})):[];if(!s.chats.length)s.chats=[blankChat()];s.current=s.chats.some(c=>c.id===s.current)?s.current:s.chats[0].id;return s}
function currentChat(){return state&&state.chats.find(c=>c.id===current)||null}

function compactState(s){const c=clone(s);c.chats.forEach(chat=>chat.messages.forEach(m=>{(m.attachments||[]).forEach(a=>{if(a.kind==='image'){if(a.thumb)a.data=a.thumb}else if(a.text&&a.text.length>30000)a.text=a.text.slice(0,30000)})}));return c}
async function persistNow(){if(!state)return;state.current=current;const key=stateKey(apiKey);const full=clone(state);dbPut(key,full);const ok=lsSet('sliq-v15-'+hashKey(apiKey||'guest'),JSON.stringify(compactState(full)));lsSet('sliq-web-chats',JSON.stringify(full.chats));lsSet('sliq-web-lang',lang);lsSet('sliqadius-lang',lang);lsSet('sliq-web-mode',mode);lsSet('sliq-v15-theme',theme);if(apiKey){lsSet('sliq-web-key',apiKey);dbPut('api-key',apiKey)}if(!ok&&!storageWarned){storageWarned=true;toast(ui.storageError)}if($('saveHint'))$('saveHint').textContent=ui.saved||'Saved automatically'}
function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(persistNow,120)}
async function loadStateForKey(key){let saved=await dbGet(stateKey(key));if(!saved){try{saved=JSON.parse(lsGet('sliq-v15-'+hashKey(key||'guest'),''))}catch(e){saved=null}}if(!saved){let legacy=[];try{legacy=JSON.parse(lsGet('sliq-web-chats','[]'));if(!Array.isArray(legacy))legacy=[]}catch(e){}if(legacy.length)saved={version:15,chats:legacy,memories:[],usage:defaultState().usage,current:legacy[0].id};}return normalizeState(saved)}
async function switchApiKey(newKey,copyGuest){newKey=String(newKey||'').trim();if(state)await persistNow();const old=apiKey;apiKey=newKey;lsSet('sliq-web-key',apiKey);if(apiKey)await dbPut('api-key',apiKey);let existing=await dbGet(stateKey(apiKey));if(!existing){try{existing=JSON.parse(lsGet('sliq-v15-'+hashKey(apiKey||'guest'),''))}catch(e){existing=null}}if(!existing&&copyGuest&&!old&&state){state=normalizeState(clone(state));await dbPut(stateKey(apiKey),state)}else state=await loadStateForKey(apiKey);current=state.current;renderAll();persistNow();toast(ui.apiKeyChanged)}

async function loadUi(code){lang=normLang(code);let base={};try{if(window.SliqI18nLoader){const d=await SliqI18nLoader.load(lang);base=d&&d.web||{}}}catch(e){}ui=Object.assign({},FALLBACK,base,EXTRA[lang]||EXTRA.en);document.documentElement.lang=lang;lsSet('sliq-web-lang',lang);lsSet('sliqadius-lang',lang)}
function t(k,f){return ui[k]||f||k}

function applyTheme(){let resolved=theme;if(theme==='system')resolved=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';document.body.dataset.theme=resolved;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=resolved==='light'?'#f4f6f4':'#101311';document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme));if($('themeBtn'))$('themeBtn').textContent='◐  '+t('appearance','Appearance')}

function fillLanguages(){['langSide','langTop'].forEach(id=>{const s=$(id);if(!s)return;s.innerHTML='';Object.keys(LANGS).forEach(code=>{const o=document.createElement('option');o.value=code;o.textContent=LANGS[code];s.appendChild(o)});s.value=lang})}
function modeLabel(){return mode==='fast'?t('fast'):mode==='smart'?t('smart'):t('medium')}
function applyText(){
  if($('newChatBtn'))$('newChatBtn').textContent=t('newChat');
  if($('chatSearch'))$('chatSearch').placeholder=t('search');
  if($('memoryBtn'))$('memoryBtn').textContent='◫  '+t('memory');
  if($('changeKeyBtn'))$('changeKeyBtn').textContent='◇  '+t('changeKey');
  if($('exportBtn'))$('exportBtn').textContent='⇩  '+t('backup');
  if($('importBtn'))$('importBtn').textContent='⇧  '+t('restore');
  if($('installAppBtn'))$('installAppBtn').textContent='⊕  '+t('installApp');
  if($('installLink'))$('installLink').textContent=t('install');
  if($('backLink'))$('backLink').textContent=t('back');
  if($('messageInput'))$('messageInput').placeholder=t('placeholder');
  if($('langLabel'))$('langLabel').textContent=t('language');
  if($('note'))$('note').textContent=t('note');
  if($('modeBtn'))$('modeBtn').textContent=modeLabel()+'⌄';
  const mb=$('modeMenu')&&$('modeMenu').querySelectorAll('[data-mode]');if(mb&&mb.length===3){mb[0].textContent=t('fast');mb[1].textContent=t('medium');mb[2].textContent=t('smart')}
  if($('usageBtn'))$('usageBtn').textContent='◌ '+t('usage');
  if($('keyTitle'))$('keyTitle').textContent='Groq API Key';
  if($('keyText'))$('keyText').textContent=t('keyText');
  if($('keyHint'))$('keyHint').textContent=t('keyHint');
  if($('cancelKeyBtn'))$('cancelKeyBtn').textContent=t('cancel');
  if($('saveKeyBtn'))$('saveKeyBtn').textContent=t('save');
  if($('getKeyLink'))$('getKeyLink').textContent=t('getKey');
  if($('renameTitle'))$('renameTitle').textContent=t('renameTitle');
  if($('renameCancel'))$('renameCancel').textContent=t('cancel');
  if($('renameSave'))$('renameSave').textContent=t('save');
  if($('editTitle'))$('editTitle').textContent=t('editTitle');
  if($('editCancel'))$('editCancel').textContent=t('cancel');
  if($('editSave'))$('editSave').textContent=t('saveRegenerate');
  if($('memoryTitle'))$('memoryTitle').textContent=t('memoryTitle');
  if($('memoryHint'))$('memoryHint').textContent=t('memoryHint');
  if($('memoryInput'))$('memoryInput').placeholder=t('memoryPlaceholder');
  if($('memoryAdd'))$('memoryAdd').textContent=t('addMemory');
  if($('memoryClose'))$('memoryClose').textContent=t('cancel');
  if($('appearanceTitle'))$('appearanceTitle').textContent=t('appearanceTitle');
  if($('appearanceClose'))$('appearanceClose').textContent=t('cancel');
  if($('usageTitle'))$('usageTitle').textContent=t('usageTitle');
  if($('usageClose'))$('usageClose').textContent=t('cancel');
  if($('usageClear'))$('usageClear').textContent=t('clear');
  document.querySelectorAll('[data-theme-choice="system"]').forEach(b=>b.textContent=t('themeSystem'));
  document.querySelectorAll('[data-theme-choice="dark"]').forEach(b=>b.textContent=t('themeDark'));
  document.querySelectorAll('[data-theme-choice="light"]').forEach(b=>b.textContent=t('themeLight'));
  updateBadge();updateComposer();applyTheme();renderPending();renderMemory();renderUsage();
}
function updateBadge(){const b=$('apiBadge');if(!b)return;b.textContent=apiKey?t('apiReady'):t('apiMissing');b.classList.toggle('ready',!!apiKey)}

function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),1900)}
function openModal(id){$(id)&&$(id).classList.add('open')}
function closeModal(id){$(id)&&$(id).classList.remove('open')}
function closeMenu(){$('side')&&$('side').classList.remove('open');$('shade')&&$('shade').classList.remove('open')}
function openMenu(){$('side')&&$('side').classList.add('open');$('shade')&&$('shade').classList.add('open')}
function scrollBottom(behavior='auto'){const box=$('messages');if(!box)return;requestAnimationFrame(()=>{try{box.scrollTo({top:box.scrollHeight,behavior})}catch(e){box.scrollTop=box.scrollHeight}})}

function newChat(){const c=blankChat();state.chats.unshift(c);current=c.id;state.current=current;persistNow();renderAll();closeMenu();$('messageInput').focus()}
function deleteChat(id){if(!confirm(t('confirmDelete')))return;state.chats=state.chats.filter(c=>c.id!==id);if(!state.chats.length)state.chats=[blankChat()];if(!state.chats.some(c=>c.id===current))current=state.chats[0].id;persistNow();renderAll()}
function togglePin(id){const c=state.chats.find(x=>x.id===id);if(!c)return;c.pinned=!c.pinned;c.updated=Date.now();persist();renderHistory()}
function openRename(c){renameId=c.id;$('renameInput').value=c.title||'';openModal('renameModal');setTimeout(()=>{$('renameInput').focus();$('renameInput').select()},30)}
function saveRename(){const v=$('renameInput').value.trim();const c=state.chats.find(x=>x.id===renameId);if(v&&c){c.title=v.slice(0,80);c.updated=Date.now();persistNow();renderHistory()}closeModal('renameModal');renameId=null}

function renderHistory(){const h=$('history');if(!h||!state)return;h.innerHTML='';const q=searchTerm.trim().toLowerCase();const list=state.chats.slice().sort((a,b)=>(Number(b.pinned)-Number(a.pinned))||((b.updated||0)-(a.updated||0))).filter(c=>{if(!q)return true;const text=[c.title].concat((c.messages||[]).map(m=>m.content)).concat((c.messages||[]).flatMap(m=>(m.attachments||[]).map(a=>a.name))).join(' ').toLowerCase();return text.includes(q)});list.forEach(c=>{const row=document.createElement('div');row.className='chatrow'+(c.id===current?' active':'');if(c.pinned)row.classList.add('pinned');const b=document.createElement('button');b.type='button';b.className='chat';b.textContent=c.title||'Chat';b.onclick=()=>{current=c.id;state.current=current;renderHistory();renderMessages();closeMenu();scrollBottom('auto')};const tools=document.createElement('div');tools.className='chattools';const pin=document.createElement('button');pin.type='button';pin.className='iconbtn'+(c.pinned?' active':'');pin.title=c.pinned?t('unpin'):t('pin');pin.textContent='◆';pin.onclick=e=>{e.stopPropagation();togglePin(c.id)};const rn=document.createElement('button');rn.type='button';rn.className='iconbtn';rn.title=t('rename');rn.textContent='✎';rn.onclick=e=>{e.stopPropagation();openRename(c)};const del=document.createElement('button');del.type='button';del.className='iconbtn danger';del.title=t('del');del.textContent='×';del.onclick=e=>{e.stopPropagation();deleteChat(c.id)};tools.append(pin,rn,del);row.append(b,tools);h.appendChild(row)})}

function attachmentLabel(a){if(a.kind==='image')return'▧ '+a.name;if(a.kind==='pdf')return'PDF '+a.name;return'⌘ '+a.name}
function appendAttachmentBadges(parent,atts){if(!atts||!atts.length)return;const box=document.createElement('div');box.className='msgfiles';atts.forEach(a=>{const chip=document.createElement('span');chip.className='msgfile';chip.textContent=attachmentLabel(a);box.appendChild(chip)});parent.appendChild(box)}
function renderRich(container,text){container.innerHTML='';const parts=String(text||'').split('```');parts.forEach((part,i)=>{if(i%2===0){if(!part)return;const d=document.createElement('div');d.className='textpart';d.textContent=part;container.appendChild(d)}else{let langName='',code=part;const p=part.indexOf('\n');if(p>=0){langName=part.slice(0,p).trim().slice(0,20);code=part.slice(p+1)}const pre=document.createElement('div');pre.className='codeblock';const head=document.createElement('div');head.className='codehead';const label=document.createElement('span');label.textContent=langName||t('code');const cp=document.createElement('button');cp.type='button';cp.textContent=t('copyCode');cp.onclick=()=>copyText(code);head.append(label,cp);const body=document.createElement('pre');body.textContent=code;pre.append(head,body);container.appendChild(pre)}})}
function messageTools(m,index){const tools=document.createElement('div');tools.className='msgtools';const add=(label,txt,fn,active)=>{const b=document.createElement('button');b.type='button';b.title=label;b.textContent=txt;b.classList.toggle('active',!!active);b.onclick=fn;tools.appendChild(b)};add(t('copy'),t('copy'),()=>copyText(m.content||''));if(m.role==='user'){add(t('edit'),'✎ '+t('edit'),()=>openEdit(m));add(t('rememberThis'),'◫',()=>rememberMessage(m))}else{add(t('regenerate'),'↻',()=>regenerateAt(index));add(t('like'),'👍',()=>setFeedback(m.id,'up'),m.feedback==='up');add(t('dislike'),'👎',()=>setFeedback(m.id,'down'),m.feedback==='down');add(t('speak'),'◖',()=>speakText(m.content||''))}return tools}
function renderMessages(){const box=$('messages'),c=currentChat();if(!box)return;box.innerHTML='';if(!c||!(c.messages||[]).length){const emp=document.createElement('div');emp.className='empty';const inner=document.createElement('div');inner.className='emptyinner';inner.innerHTML='<img class="emptylogo" src="logo-approved.jpg" alt=""><h1></h1><p></p><div class="suggestions"></div>';inner.querySelector('h1').textContent=t('welcome');inner.querySelector('p').textContent=t('hint');[t('suggest1'),t('suggest2'),t('suggest3')].forEach(txt=>{const s=document.createElement('button');s.type='button';s.className='suggestion';s.textContent=txt;s.onclick=()=>{$('messageInput').value=txt;resizeInput();updateComposer();$('messageInput').focus()};inner.querySelector('.suggestions').appendChild(s)});emp.appendChild(inner);box.appendChild(emp);return}c.messages.forEach((m,index)=>{const row=document.createElement('div');row.className='row '+(m.role==='user'?'user':'assistant');row.dataset.mid=m.id;const wrap=document.createElement('div');wrap.className='msgwrap';const bubble=document.createElement('div');bubble.className='bubble'+(m.streaming?' streaming':'');(m.attachments||[]).filter(a=>a.kind==='image'&&(a.thumb||a.data)).forEach(a=>{const im=document.createElement('img');im.src=a.thumb||a.data;im.alt=a.name||'';bubble.appendChild(im)});appendAttachmentBadges(bubble,(m.attachments||[]).filter(a=>a.kind!=='image'));const tx=document.createElement('div');tx.className='message-text';if(m.streaming)tx.textContent=m.content||t('thinking');else renderRich(tx,m.content||'');bubble.appendChild(tx);wrap.appendChild(bubble);if(!m.streaming)wrap.appendChild(messageTools(m,index));row.appendChild(wrap);box.appendChild(row)});scrollBottom(busy?'auto':'smooth')}
function updateStreamingMessage(id,text){const row=document.querySelector('[data-mid="'+CSS.escape(id)+'"]');if(!row)return;const tx=row.querySelector('.message-text');if(tx)tx.textContent=text||t('thinking');scrollBottom('auto')}

function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(()=>toast(t('copied'))).catch(()=>fallbackCopy(text));else fallbackCopy(text)}
function fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');toast(t('copied'))}catch(e){}ta.remove()}
function setFeedback(id,val){const c=currentChat();const m=c&&c.messages.find(x=>x.id===id);if(!m)return;m.feedback=m.feedback===val?null:val;persist();renderMessages();toast(t('feedbackSaved'))}
function rememberMessage(m){const v=String(m.content||'').trim().slice(0,500);if(!v)return;if(!state.memories.some(x=>x.text===v))state.memories.unshift({id:uid('mem'),text:v,created:Date.now()});persist();renderMemory();toast(t('saved'))}

function openEdit(m){editId=m.id;$('editInput').value=m.content||'';openModal('editModal');setTimeout(()=>{$('editInput').focus();$('editInput').select()},30)}
async function saveEditAndRegenerate(){const c=currentChat();if(!c)return;const idx=c.messages.findIndex(m=>m.id===editId);if(idx<0)return;const val=$('editInput').value.trim();if(!val)return;c.messages[idx].content=val;c.messages=c.messages.slice(0,idx+1);c.updated=Date.now();closeModal('editModal');editId=null;persistNow();renderMessages();renderHistory();await generateAssistant()}
async function regenerateAt(index){if(busy)return;const c=currentChat();if(!c)return;let cut=index;if(c.messages[index]&&c.messages[index].role==='assistant')c.messages=c.messages.slice(0,cut);else c.messages=c.messages.slice(0,cut+1);while(c.messages.length&&c.messages[c.messages.length-1].role==='assistant')c.messages.pop();if(!c.messages.length||c.messages[c.messages.length-1].role!=='user')return;c.updated=Date.now();persistNow();renderMessages();await generateAssistant()}

function renderMemory(){const list=$('memoryList');if(!list||!state)return;list.innerHTML='';if(!state.memories.length){const e=document.createElement('div');e.className='emptylist';e.textContent=t('noMemories');list.appendChild(e);return}state.memories.forEach(mem=>{const row=document.createElement('div');row.className='memoryrow';const text=document.createElement('div');text.textContent=mem.text;const del=document.createElement('button');del.type='button';del.textContent='×';del.title=t('remove');del.onclick=()=>{state.memories=state.memories.filter(x=>x.id!==mem.id);persist();renderMemory()};row.append(text,del);list.appendChild(row)})}
function addMemory(){const v=$('memoryInput').value.trim();if(!v)return;state.memories.unshift({id:uid('mem'),text:v.slice(0,500),created:Date.now()});$('memoryInput').value='';persist();renderMemory()}

function showKey(required,retry){retryAfterKey=!!retry;$('keyStatus').textContent=required?t('keyRequired'):'';$('keyInput').value=apiKey;openModal('keyModal');setTimeout(()=>$('keyInput').focus(),30)}
async function saveKey(){const v=$('keyInput').value.trim();if(!/^gsk_[A-Za-z0-9_-]{12,}$/.test(v)){$('keyStatus').textContent=t('invalid');return}const copyGuest=!apiKey;closeModal('keyModal');await switchApiKey(v,copyGuest);if(retryAfterKey){retryAfterKey=false;setTimeout(()=>sendMessage(),80)}}

function renderPending(){const box=$('attachmentChips');if(!box)return;box.innerHTML='';box.classList.toggle('show',pending.length>0);pending.forEach(a=>{const chip=document.createElement('div');chip.className='filechip';if(a.kind==='image'&&a.thumb){const im=document.createElement('img');im.src=a.thumb;im.alt='';chip.appendChild(im)}const label=document.createElement('span');label.textContent=attachmentLabel(a);const del=document.createElement('button');del.type='button';del.textContent='×';del.onclick=()=>{pending=pending.filter(x=>x.id!==a.id);renderPending();updateComposer()};chip.append(label,del);box.appendChild(chip)})}
function processImage(file){return new Promise((resolve,reject)=>{if(file.size>20*1024*1024){reject(new Error('TOO_LARGE'));return}const r=new FileReader();r.onerror=reject;r.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{function render(max,q){const sc=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight));const w=Math.max(1,Math.round(im.naturalWidth*sc)),h=Math.max(1,Math.round(im.naturalHeight*sc));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(im,0,0,w,h);return c.toDataURL('image/jpeg',q)}resolve({id:uid('a'),kind:'image',name:file.name||'image',mime:'image/jpeg',data:render(1200,.72),thumb:render(460,.64)})};im.src=r.result};r.readAsDataURL(file)})}
function isTextFile(file){const ext=(file.name.split('.').pop()||'').toLowerCase();return (file.type&&file.type.startsWith('text/'))||['txt','md','json','js','ts','tsx','jsx','py','java','kt','kts','html','htm','css','scss','xml','yaml','yml','csv','log','sql','c','h','cpp','hpp','cs','go','rs','php','rb','sh','ps1','bat','ini','toml'].includes(ext)}
function readText(file){return new Promise((resolve,reject)=>{if(file.size>8*1024*1024){reject(new Error('TOO_LARGE'));return}const r=new FileReader();r.onerror=reject;r.onload=()=>resolve({id:uid('a'),kind:'file',name:file.name||'file',mime:file.type||'text/plain',text:String(r.result||'').slice(0,80000)});r.readAsText(file)})}
async function readPdf(file){if(file.size>12*1024*1024)throw new Error('TOO_LARGE');if(!pdfModulePromise)pdfModulePromise=import(PDFJS_URL);const pdfjs=await pdfModulePromise;pdfjs.GlobalWorkerOptions.workerSrc=PDFJS_WORKER;const data=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjs.getDocument({data}).promise;let out='';const max=Math.min(pdf.numPages,80);for(let i=1;i<=max;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();out+='\n\n[Page '+i+']\n'+content.items.map(x=>x.str).join(' ');if(out.length>100000)break}return{id:uid('a'),kind:'pdf',name:file.name||'document.pdf',mime:'application/pdf',text:out.slice(0,100000)}}
async function addAttachment(file){if(!file)return;if(pending.length>=5){toast(t('maxAttachments'));return}try{let a;if(file.type&&file.type.startsWith('image/'))a=await processImage(file);else if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))a=await readPdf(file);else if(isTextFile(file))a=await readText(file);else throw new Error('UNSUPPORTED');pending.push(a);renderPending();updateComposer();toast(t('fileAdded'))}catch(e){const s=String(e&&e.message||e);toast(s.includes('TOO_LARGE')?t('fileTooLarge'):s.includes('UNSUPPORTED')?t('unsupportedFile'):file.type==='application/pdf'?t('pdfFailed'):t('error'))}}

function memoryPrompt(){if(!state||!state.memories.length)return'';return'\n\nUser memories explicitly saved locally:\n'+state.memories.slice(0,30).map(x=>'- '+x.text).join('\n')}
function systemPrompt(){const mi=mode==='fast'?'Prioritize speed and concise useful answers.':mode==='smart'?'Prioritize correctness. Silently verify assumptions, calculations, code and edge cases before answering.':'Balance speed and correctness. Silently verify important claims.';return'You are Sliqadius, a capable general AI assistant. Preferred language: '+(LANGS[lang]||'English')+'. Reply in that language by default unless the user clearly requests another language. '+mi+' Follow conversation context, do not invent facts, and provide complete runnable code when appropriate. Never reveal private chain-of-thought.'+memoryPrompt()}
function messageText(m){let text=String(m.content||'');let total=0;(m.attachments||[]).forEach(a=>{if(a.kind==='file'||a.kind==='pdf'){const part=String(a.text||'').slice(0,35000);if(part&&total<70000){text+='\n\n--- Attached file: '+a.name+' ---\n'+part;total+=part.length}}});return text}
function buildPayload(messages){const recent=messages.slice(-24);const latest=recent[recent.length-1];const images=latest&&latest.role==='user'?(latest.attachments||[]).filter(a=>a.kind==='image'&&(a.data||a.thumb)).slice(0,2):[];if(images.length){const prior=recent.slice(0,-1).map(m=>({role:m.role,content:messageText(m)}));const content=[{type:'text',text:systemPrompt()+'\n\nUser question and file context:\n'+messageText(latest)}];images.forEach(a=>content.push({type:'image_url',image_url:{url:a.data||a.thumb}}));return{model:VISION,messages:prior.concat([{role:'user',content}]),temperature:.55,max_completion_tokens:mode==='smart'?1900:mode==='medium'?1400:900,reasoning_effort:mode==='fast'?'none':'default',reasoning_format:'hidden',stream:true}}return{model:mode==='fast'?TEXT_FAST:TEXT_SMART,messages:[{role:'system',content:systemPrompt()}].concat(recent.map(m=>({role:m.role,content:messageText(m)}))),temperature:.45,max_completion_tokens:mode==='fast'?1800:mode==='smart'?4200:3000,reasoning_effort:mode==='fast'?'low':mode==='smart'?'high':'medium',include_reasoning:false,stream:true}}
function rateFromHeaders(h){return{remainingRequests:h.get('x-ratelimit-remaining-requests')||'',remainingTokens:h.get('x-ratelimit-remaining-tokens')||'',requestReset:h.get('x-ratelimit-reset-requests')||'',tokenReset:h.get('x-ratelimit-reset-tokens')||'',limitRequests:h.get('x-ratelimit-limit-requests')||'',limitTokens:h.get('x-ratelimit-limit-tokens')||''}}
function estimateTokens(s){return Math.max(1,Math.ceil(String(s||'').length/4))}
function recordUsage(payload,text,model,usage,headers){const u=state.usage;u.requests=Number(u.requests||0)+1;let input=0,output=0,total=0,exact=false;if(usage){input=Number(usage.prompt_tokens||usage.input_tokens||0);output=Number(usage.completion_tokens||usage.output_tokens||0);total=Number(usage.total_tokens||input+output);exact=!!total}if(!total){input=estimateTokens(JSON.stringify(payload.messages||[]));output=estimateTokens(text);total=input+output}u.inputTokens=Number(u.inputTokens||0)+input;u.outputTokens=Number(u.outputTokens||0)+output;u.totalTokens=Number(u.totalTokens||0)+total;u.estimated=!(exact&&u.estimated===false?true:exact);if(exact)u.estimated=false;u.lastModel=model||payload.model||'';if(headers)u.rate=rateFromHeaders(headers);persist();renderUsage()}
async function streamRequest(payload,onDelta){let attempt=0;while(true){activeController=new AbortController();let resp;try{resp=await fetch(API,{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:activeController.signal,cache:'no-store'})}catch(e){if(e.name==='AbortError')throw e;if(attempt++<1){await new Promise(r=>setTimeout(r,700));continue}throw e}if(!resp.ok){const txt=await resp.text().catch(()=> '');const e=new Error('HTTP '+resp.status+' '+txt);e.status=resp.status;if([408,425,500,502,503,504].includes(resp.status)&&attempt++<1){await new Promise(r=>setTimeout(r,900));continue}throw e}const headers=resp.headers;let out='',usage=null;if(!resp.body){const j=await resp.json();out=j&&j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content||'';usage=j&&j.usage||null;onDelta(out);return{text:out,usage,headers}}const reader=resp.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split(/\r?\n/);buf=lines.pop()||'';for(const line of lines){const s=line.trim();if(!s.startsWith('data:'))continue;const data=s.slice(5).trim();if(!data||data==='[DONE]')continue;try{const j=JSON.parse(data);if(j.usage)usage=j.usage;const delta=j&&j.choices&&j.choices[0]&&j.choices[0].delta&&j.choices[0].delta.content;if(delta){out+=delta;onDelta(delta)}}catch(e){}}}return{text:out,usage,headers}}
function userError(e){const s=String(e&&e.message||e).toLowerCase();if(s.includes('401'))return'🔑 '+t('unauth');if(s.includes('429'))return'⏳ '+t('limit');if(s.includes('failed to fetch')||s.includes('network'))return'📡 '+t('network');return'⚠️ '+t('error')}

async function generateAssistant(){if(busy)return;const c=currentChat();if(!c||!c.messages.length||c.messages[c.messages.length-1].role!=='user')return;if(!apiKey){showKey(true,true);return}busy=true;stopping=false;const assistant={id:uid('m'),role:'assistant',content:'',attachments:[],feedback:null,created:Date.now(),streaming:true};c.messages.push(assistant);c.updated=Date.now();renderMessages();renderHistory();updateComposer();const prior=c.messages.slice(0,-1);const payload=buildPayload(prior);try{const res=await streamRequest(payload,delta=>{assistant.content+=delta;updateStreamingMessage(assistant.id,assistant.content)});assistant.streaming=false;if(!assistant.content.trim())assistant.content=res.text||t('error');recordUsage(payload,assistant.content,payload.model,res.usage,res.headers)}catch(e){assistant.streaming=false;if(e&&e.name==='AbortError'){if(!assistant.content.trim())c.messages=c.messages.filter(m=>m.id!==assistant.id);toast(t('streamStopped'))}else{if(!assistant.content.trim())assistant.content=userError(e);else toast(userError(e))}}finally{activeController=null;busy=false;stopping=false;c.updated=Date.now();persistNow();renderHistory();renderMessages();updateComposer();$('messageInput').focus()}}
function stopGeneration(){if(!busy||!activeController)return;stopping=true;try{activeController.abort()}catch(e){}}
async function sendMessage(){if(busy){stopGeneration();return}const text=$('messageInput').value.trim();if(!text&&!pending.length)return;if(!apiKey){showKey(true,true);return}const c=currentChat();if(!c)return;const shown=text||((pending.some(a=>a.kind==='image'))?t('imageQ'):'Please analyze the attached file.');const msg={id:uid('m'),role:'user',content:shown,attachments:clone(pending),feedback:null,created:Date.now(),streaming:false};c.messages.push(msg);c.updated=Date.now();if(c.messages.filter(m=>m.role==='user').length===1)c.title=shown.slice(0,42)+(shown.length>42?'…':'');$('messageInput').value='';resizeInput();pending=[];renderPending();persistNow();renderHistory();renderMessages();updateComposer();await generateAssistant()}
function updateComposer(){const send=$('sendBtn');if(!send)return;if(busy){send.disabled=false;send.textContent='■';send.classList.add('stop');send.setAttribute('aria-label',t('stop'));send.title=t('stop')}else{const ok=!!($('messageInput').value.trim()||pending.length);send.disabled=!ok;send.textContent='↑';send.classList.remove('stop');send.setAttribute('aria-label',t('send'));send.title=t('send')}if($('micBtn'))$('micBtn').title=t('mic')}
function resizeInput(){const i=$('messageInput');if(!i)return;i.style.height='auto';i.style.height=Math.min(154,i.scrollHeight)+'px'}

function speakText(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||''));u.lang=SPEECH_LANG[lang]||'en-US';u.rate=1;window.speechSynthesis.speak(u)}
function toggleMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast(t('micUnavailable'));return}if(recognition){try{recognition.stop()}catch(e){}return}recognition=new SR();recognition.lang=SPEECH_LANG[lang]||'en-US';recognition.interimResults=true;recognition.continuous=false;recognitionBase=$('messageInput').value;const b=$('micBtn');b.classList.add('listening');recognition.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const tx=e.results[i][0].transcript;if(e.results[i].isFinal)final+=tx;else interim+=tx}$('messageInput').value=(recognitionBase+(recognitionBase?' ':'')+final+interim).trimStart();resizeInput();updateComposer()};recognition.onerror=()=>{};recognition.onend=()=>{recognition=null;b.classList.remove('listening');resizeInput();updateComposer()};try{recognition.start()}catch(e){recognition=null;b.classList.remove('listening')}}

function renderUsage(){if(!state||!$('usageGrid'))return;const u=state.usage||defaultState().usage,r=u.rate||{};const tokenLabel=(u.estimated?'≈ ':'')+Number(u.totalTokens||0).toLocaleString();const rows=[[t('requests'),Number(u.requests||0).toLocaleString()],[t('tokens'),tokenLabel],[t('inputTokens'),Number(u.inputTokens||0).toLocaleString()],[t('outputTokens'),Number(u.outputTokens||0).toLocaleString()],[t('remainingRequests'),r.remainingRequests||t('notAvailable')],[t('remainingTokens'),r.remainingTokens||t('notAvailable')],[t('requestReset'),r.requestReset||t('notAvailable')],[t('tokenReset'),r.tokenReset||t('notAvailable')],[t('lastModel'),u.lastModel||t('notAvailable')]];$('usageGrid').innerHTML='';rows.forEach(([k,v])=>{const d=document.createElement('div');d.className='stat';const a=document.createElement('span');a.textContent=k;const b=document.createElement('strong');b.textContent=v;d.append(a,b);$('usageGrid').appendChild(d)});if($('usageNote'))$('usageNote').textContent=(u.estimated?t('estimated')+' · ':'')+t('localOnly')}
function clearUsage(){state.usage=defaultState().usage;persist();renderUsage()}

function exportData(){const data={version:15,exportedAt:new Date().toISOString(),state:clone(state),lang,mode,theme};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Sliqadius-Backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},200);toast(t('backupDone'))}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);const incoming=d.state||{chats:d.chats,memories:d.memories,usage:d.usage};state=normalizeState(incoming);current=state.current;if(d.lang&&LANGS[d.lang])lang=d.lang;if(['fast','medium','smart'].includes(d.mode))mode=d.mode;if(['system','dark','light'].includes(d.theme))theme=d.theme;loadUi(lang).then(()=>{fillLanguages();applyText();persistNow();renderAll();toast(t('restoreDone'))})}catch(e){toast(t('error'))}};r.readAsText(file)}

function installPwa(){if(matchMedia('(display-mode: standalone)').matches){toast(t('installed'));return}if(deferredInstall){deferredInstall.prompt();deferredInstall.userChoice.finally(()=>{deferredInstall=null})}else toast(t('installUnavailable'))}

function renderAll(){fillLanguages();applyText();renderHistory();renderMessages();renderMemory();renderUsage();renderPending();updateComposer();scrollBottom('auto')}
async function setLanguage(code){await loadUi(code);fillLanguages();applyText();renderAll();persist()}

function wire(){
  $('newChatBtn').onclick=newChat;$('chatSearch').oninput=function(){searchTerm=this.value;renderHistory()};$('memoryBtn').onclick=()=>openModal('memoryModal');$('themeBtn').onclick=()=>openModal('appearanceModal');$('changeKeyBtn').onclick=()=>showKey(false,false);$('apiBadge').onclick=()=>showKey(false,false);$('usageBtn').onclick=()=>{renderUsage();openModal('usageModal')};$('menuBtn').onclick=openMenu;$('shade').onclick=closeMenu;
  $('langSide').onchange=function(){setLanguage(this.value)};$('langTop').onchange=function(){setLanguage(this.value)};
  $('attachBtn').onclick=e=>{e.stopPropagation();$('attachMenu').classList.toggle('open')};$('attachImageBtn').onclick=()=>{const f=$('fileInput');f.accept='image/png,image/jpeg,image/webp,image/gif';f.click();$('attachMenu').classList.remove('open')};$('attachFileBtn').onclick=()=>{const f=$('fileInput');f.accept='.pdf,.txt,.md,.json,.js,.ts,.tsx,.jsx,.py,.java,.kt,.kts,.html,.htm,.css,.scss,.xml,.yaml,.yml,.csv,.log,.sql,.c,.h,.cpp,.hpp,.cs,.go,.rs,.php,.rb,.sh,.ps1,.bat,.ini,.toml,text/*,application/pdf';f.click();$('attachMenu').classList.remove('open')};$('fileInput').onchange=async function(){const fs=Array.from(this.files||[]);this.value='';for(const f of fs)await addAttachment(f)};
  document.addEventListener('click',e=>{if(!$('attachBtn').contains(e.target)&&!$('attachMenu').contains(e.target))$('attachMenu').classList.remove('open');if(!$('modeBtn').contains(e.target)&&!$('modeMenu').contains(e.target))$('modeMenu').classList.remove('open')});
  $('sendBtn').onclick=sendMessage;$('messageInput').oninput=()=>{resizeInput();updateComposer()};$('messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendMessage()}};$('micBtn').onclick=toggleMic;
  $('modeBtn').onclick=e=>{e.stopPropagation();$('modeMenu').classList.toggle('open')};$('modeMenu').querySelectorAll('[data-mode]').forEach(b=>b.onclick=function(){mode=this.dataset.mode;lsSet('sliq-web-mode',mode);$('modeMenu').classList.remove('open');applyText();persist()});
  $('cancelKeyBtn').onclick=()=>{closeModal('keyModal');retryAfterKey=false};$('saveKeyBtn').onclick=saveKey;$('keyInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveKey()}};
  $('renameCancel').onclick=()=>{closeModal('renameModal');renameId=null};$('renameSave').onclick=saveRename;$('renameInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveRename()}if(e.key==='Escape')closeModal('renameModal')};
  $('editCancel').onclick=()=>{closeModal('editModal');editId=null};$('editSave').onclick=saveEditAndRegenerate;
  $('memoryAdd').onclick=addMemory;$('memoryClose').onclick=()=>closeModal('memoryModal');$('memoryInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();addMemory()}};
  $('appearanceClose').onclick=()=>closeModal('appearanceModal');document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=function(){theme=this.dataset.themeChoice;applyTheme();persist()});
  $('usageClose').onclick=()=>closeModal('usageModal');$('usageClear').onclick=clearUsage;
  $('exportBtn').onclick=exportData;$('importBtn').onclick=()=>$('importInput').click();$('importInput').onchange=function(){const f=this.files&&this.files[0];this.value='';importData(f)};$('installAppBtn').onclick=installPwa;
  $('mainArea').addEventListener('dragover',e=>e.preventDefault());$('mainArea').addEventListener('drop',async e=>{e.preventDefault();for(const f of Array.from(e.dataTransfer&&e.dataTransfer.files||[]).slice(0,5))await addAttachment(f)});$('messageInput').addEventListener('paste',async e=>{const items=Array.from(e.clipboardData&&e.clipboardData.items||[]);for(const item of items){if(item.type&&item.type.startsWith('image/')){const f=item.getAsFile();if(f)await addAttachment(f)}}});
  window.addEventListener('beforeunload',()=>{persistNow();if(window.speechSynthesis)window.speechSynthesis.cancel()});window.addEventListener('resize',()=>scrollBottom('auto'));window.addEventListener('orientationchange',()=>setTimeout(()=>scrollBottom('auto'),100));
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('appinstalled',()=>{deferredInstall=null;toast(t('installed'))});
  matchMedia('(prefers-color-scheme: light)').addEventListener&&matchMedia('(prefers-color-scheme: light)').addEventListener('change',()=>{if(theme==='system')applyTheme()});
}

async function start(){
  await openDb();if(!apiKey){const backup=await dbGet('api-key');if(backup){apiKey=String(backup);lsSet('sliq-web-key',apiKey)}}await loadUi(lang);state=await loadStateForKey(apiKey);current=state.current;applyTheme();wire();renderAll();persistNow();$('messageInput').focus();if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
}

start().catch(e=>{console.error(e);alert('Sliqadius Web could not be loaded completely. Please reload the page.')});
})();
