R.shadowMap.type=T.PCFSoftShadowMap;R.toneMapping=T.ACESFilmicToneMapping;R.toneMappingExposure=1.07;S.background.set(0xa5c3d1);S.fog.color.set(0xb7cdd5);S.fog.density=.0036;sun.intensity=3.15;sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.0002;
function tx(c,n=18){let a=document.createElement('canvas');a.width=a.height=128;let x=a.getContext('2d');x.fillStyle=c;x.fillRect(0,0,128,128);for(let i=0;i<420;i++){let q=Math.random()*.08;x.fillStyle=Math.random()>.5?'rgba(255,255,255,'+q+')':'rgba(0,0,0,'+q+')';x.fillRect(Math.random()*128,Math.random()*128,1,1)}let t=new T.CanvasTexture(a);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;return t}let tg=tx('#6e9a53'),ta=tx('#363c3f'),tc=tx('#a3a49e');tg.repeat.set(20,20);ta.repeat.set(4,4);tc.repeat.set(2,2);gm.map=tg;gm.color.set(0xffffff);am.map=ta;am.color.set(0xffffff);cm.map=tc;cm.color.set(0xffffff);
let nat=new T.Group();S.add(nat);for(let i=0;i<60;i++){let x=(Math.random()-.5)*160,z=(Math.random()-.5)*160;if(Math.hypot(x,z)<18)continue;let g=new T.Group(),tr=new T.Mesh(new T.CylinderGeometry(.08,.13,.9,6),new T.MeshStandardMaterial({color:0x654a34})),cr=new T.Mesh(new T.IcosahedronGeometry(.58+Math.random()*.22,1),new T.MeshStandardMaterial({color:[0x47773e,0x568548,0x628f4e][i%3]}));tr.position.y=.45;cr.position.y=1.15;tr.castShadow=cr.castShadow=true;g.add(tr,cr);g.position.set(x,0,z);nat.add(g)}
let oh=house;house=function(b){let g=oh(b);if(['res','com','ind'].includes(b.k)){let h=b.k==='com'?4:b.k==='ind'?2:2.8,w=b.k==='ind'?3:2,d=2;g.add(B(w*1.03,.15,d*1.03,new T.MeshStandardMaterial({color:b.k==='ind'?0x606568:0x4b5559,roughness:.8}),0,h+.075,0));if(b.k==='res')g.add(B(.52,.84,.05,new T.MeshStandardMaterial({color:0x4d453e}),0,.42,d/2+.04));if(b.k==='com')g.add(B(1.2,.1,.32,new T.MeshStandardMaterial({color:0x365f70}),0,1.1,d/2+.18))}return g};buildingsBuild();
let peds=[],pedg=new T.Group();S.add(pedg);
function pm(){let g=new T.Group(),sk=new T.MeshStandardMaterial({color:[0xf0c6a2,0xc99168,0x8a5b3f][(Math.random()*3)|0]}),sh=new T.MeshStandardMaterial({color:[0x426c8a,0x8a4b4b,0x598055,0xd0b25d][(Math.random()*4)|0]}),pa=new T.MeshStandardMaterial({color:0x30383d}),al=new T.Group(),ar=new T.Group(),ll=new T.Group(),lr=new T.Group(),hd=new T.Mesh(new T.SphereGeometry(.11,9,7),sk);hd.position.y=.82;g.add(B(.22,.38,.14,sh,0,.52,0),hd);for(let d of[[al,-.16,sh,.56],[ar,.16,sh,.56],[ll,-.07,pa,.28],[lr,.07,pa,.28]]){d[0].position.set(d[1],d[3],0);d[0].add(B(.08,.34,.08,d[2],0,-.16,0));g.add(d[0])}g.userData={al,ar,ll,lr,p:Math.random()*6.28};return g}
function sp(){if(peds.length>=34||!roads.length||!buildings.length)return;let r=roads[(Math.random()*roads.length)|0];if(!validRoad(r))return;let i=(Math.random()*(r.p.length-1))|0,a=r.p[i],b=r.p[i+1],dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz)||1,side=Math.random()<.5?-1:1,g=pm();pedg.add(g);peds.push({g,r,i,t:Math.random(),s:.045+Math.random()*.025,side,nx:-dz/l,nz:dx/l,off:RT[r.t].w*.62+.38,dir:Math.random()<.5?1:-1})}
function pu(dt){if(Math.random()<dt*.55*Math.min(2,Math.max(.25,buildings.length/5)))sp();for(let i=peds.length-1;i>=0;i--){let p=peds[i];if(!roads.includes(p.r)||!validRoad(p.r)){pedg.remove(p.g);peds.splice(i,1);continue}let a=p.r.p[p.i],b=p.r.p[p.i+1],dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz)||1;p.nx=-dz/l;p.nz=dx/l;p.t+=dt*p.s*p.dir*st.speed;if(p.t>1||p.t<0){p.dir*=-1;p.t=C(p.t,0,1)}p.g.position.set(a.x+dx*p.t+p.nx*p.off*p.side,0,a.z+dz*p.t+p.nz*p.off*p.side);p.g.rotation.y=Math.atan2(dx*p.dir,dz*p.dir);let q=performance.now()*.008+p.g.userData.p,v=Math.sin(q)*.65;p.g.userData.al.rotation.x=v;p.g.userData.ar.rotation.x=-v;p.g.userData.ll.rotation.x=-v;p.g.userData.lr.rotation.x=v}}
function ix(a,b,c,d){let rx=b.x-a.x,rz=b.z-a.z,sx=d.x-c.x,sz=d.z-c.z,D=rx*sz-rz*sx;if(Math.abs(D)<1e-7)return null;let cx=c.x-a.x,cz=c.z-a.z,t=(cx*sz-cz*sx)/D,u=(cx*rz-cz*rx)/D;return t>=0&&t<=1&&u>=0&&u<=1?{t,u}:null}
function stop(r,i,t,dir){let a=r.p[i],b=r.p[i+1],axis=Math.abs(b.x-a.x)>=Math.abs(b.z-a.z)?0:1;if(axis!==Math.floor(performance.now()/2600)%2)return null;let best=null;for(let o of roads){if(o===r||!validRoad(o))continue;for(let j=0;j<o.p.length-1;j++){let q=ix(a,b,o.p[j],o.p[j+1]);if(!q)continue;let qt=C(q.t,.025,.975),d=dir>0?qt-t:t-qt;if(d>.004&&d<.085&&(!best||d<best.d))best={t:qt,d}}}return best}
let oc=car;car=function(){oc();let c=cars[cars.length-1];if(c){c.dir=1;c.wait=0}};
carsUp=function(dt){if(Math.random()<dt*.7*st.speed)car();for(let i=cars.length-1;i>=0;i--){let c=cars[i];if(!validRoad(c.r)||!roads.includes(c.r)){removeCar(c);cars.splice(i,1);continue}let m=c.r.p.length-1;c.i=C(c.i|0,0,m-1);let a=c.r.p[c.i],b=c.r.p[c.i+1];c.dir=c.dir||1;if(c.wait>0){c.wait-=dt;continue}let q=stop(c.r,c.i,c.t,c.dir);if(q){c.t=c.dir>0?Math.max(c.t,q.t-.04):Math.min(c.t,q.t+.04);c.wait=.12}else c.t+=dt*c.s*st.speed*c.dir;if(m===1){if(c.t>=1){c.t=1;c.dir=-1}if(c.t<=0){c.t=0;c.dir=1}}else{while(c.t>=1){c.t-=1;c.i=(c.i+1)%m}while(c.t<0){c.i=(c.i-1+m)%m;c.t+=1}a=c.r.p[c.i];b=c.r.p[c.i+1]}c.g.position.set(a.x+(b.x-a.x)*c.t,.03,a.z+(b.z-a.z)*c.t);c.g.rotation.y=Math.atan2((b.x-a.x)*c.dir,(b.z-a.z)*c.dir)}pu(dt)};
let od=details;details=function(){od();for(let r of roads){if(!validRoad(r))continue;for(let i=0;i<r.p.length-1;i++){let a=r.p[i],b=r.p[i+1],dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz)||1,nx=-dz/l,nz=dx/l,n=Math.floor(l/11);for(let j=1;j<=n;j++){let t=j/(n+1),x=a.x+dx*t,z=a.z+dz*t;for(let s of[-1,1]){let po=new T.Mesh(new T.CylinderGeometry(.025,.035,1.6,6),new T.MeshStandardMaterial({color:0x3b4549}));po.position.set(x+nx*(RT[r.t].w*.7+.25)*s,.8,z+nz*(RT[r.t].w*.7+.25)*s);dg.add(po)}}}}};roadsBuild();
let nc=document.getElementById('newcity');if(nc)nc.onclick=()=>{roads=[];buildings=[];for(let c of cars)removeCar(c);cars=[];for(let p of peds)pedg.remove(p.g);peds=[];st={money:100000,pop:0,happy:70,speed:1,paused:false};roadsBuild();buildingsBuild();saveGame();document.getElementById('menu').style.display='none';toast('New city started')};